google.maps.__gjsload__('streetview', function(_){'use strict';var t3=function(a){this.N=a||[]};var u3=function(a){this.N=a||[]};var v3=function(a){this.N=a||[]};var w3=function(a){this.N=a||[]};var x3=function(a){return(a=a.N[24])?new _.Fe(a):_.Hh};var y3=function(a,b){return new v3(_.Q(a.N,5)[b])};var z3=function(a){return(a=a.N[7])?new _.YM(a):_.sP};var A3=function(a){return(a=a.N[6])?new _.rM(a):_.rP};var B3=function(a){return(a=a.N[3])?new _.mM(a):_.pP};var C3=function(a){return(a=a.N[2])?new _.zM(a):_.oP};var D3=function(a,b){_.Q(a.N,0).push(b)};
var E3=function(a){a=a.N[0];return null!=a?a:0};var oca=function(a){a.N[8]=a.N[8]||[];return new _.LM(a.N[8])};var F3=function(a){a.N[10]=a.N[10]||[];return new _.FM(a.N[10])};var pca=function(a){a.N[0]=a.N[0]||[];return new _.JM(a.N[0])};var qca=function(a,b){a.N[0]=b};var rca=function(a){a.N[2]=!0};var G3=function(a){var b=[];_.Q(a.N,0).push(b);return new u3(b)};var H3=function(a){a.N[0]=a.N[0]||[];return new _.vM(a.N[0])};var I3=function(a){return(a=a.N[0])?new _.sM(a):_.sO};
var J3=function(a){return(a=a.N[3])?new _.DM(a):_.rO};var K3=function(a){this.N=a||[]};var L3=function(a){this.N=a||[]};var M3=function(a){this.N=a||[]};var N3=function(a){this.N=a||[]};var sca=function(a,b){return _.Q(a.N,1)[b]};var O3=function(a){this.N=a||[]};var P3=function(a){return(a=a.N[1])?new _.yM(a):_.pO};var Q3=function(a){return(a=a.N[3])?new _.AM(a):_.nO};var R3=function(a){return(a=a.N[2])?new _.yM(a):_.mO};var S3=function(a){a=a.N[1];return null!=a?a:0};
var T3=function(a){a=a.N[0];return null!=a?a:0};var U3=function(a){a=a.N[0];return null!=a?a:""};var tca=function(a,b){a.N[3]=b};var V3=function(a){a=a.N[3];return null!=a?a:0};var uca=function(a,b){a.N[2]=b};var W3=function(a){a=a.N[2];return null!=a?a:0};var X3=function(a){return(a=a.N[3])?new _.xM(a):_.jO};var Y3=function(a){return(a=a.N[2])?new _.wM(a):_.iO};var Z3=function(a){return(a=a.N[0])?new _.vM(a):_.hO};var $3=function(a){a=a.N[0];return null!=a?a:0};
var a4=function(a){return(a=a.N[7])?new _.lM(a):_.gO};var b4=function(a,b){return new _.jM(_.Q(a.N,2)[b])};var c4=function(a){return(a=a.N[0])?new _.jM(a):_.bO};var d4=function(a){return new w3(_.Q(a.N,1)[0])};var vca=function(a){return _.Fc(a.N,0)};var e4=function(a){a=a.N[0];return null!=a?a:""};var f4=function(a,b){var c=wca;b.cb_client=a.O;b.v=4;b.hl=_.He(_.Ke(_.R));b.gl=_.Ie(_.Ke(_.R));return c(b)};var xca=function(){var a=x3(_.R).N[9];return null!=a?a:""};
var yca=function(){var a=x3(_.R).N[8];return null!=a?a:""};var g4=function(){if(!h4){var a=[];h4={ka:-1,ma:a};a[1]={type:"i",label:1,R:0};a[2]={type:"i",label:1,R:0}}return h4};var i4=function(){if(!j4){var a=[];j4={ka:-1,ma:a};a[1]={type:"x",label:1,R:0};a[2]={type:"x",label:1,R:0}}return j4};var k4=function(){if(!l4){var a=[];l4={ka:-1,ma:a};a[1]={type:"s",label:1,R:""};a[2]={type:"s",label:1,R:""}}return l4};
var m4=function(){if(!n4){var a=[];n4={ka:-1,ma:a};a[3]={type:"d",label:1,R:0};a[4]={type:"d",label:1,R:0};a[5]={type:"e",label:1,R:1}}return n4};var o4=function(){if(!p4){var a=[];p4={ka:-1,ma:a};a[1]={type:"s",label:1,R:""};a[2]={type:"s",label:1,R:""};a[3]={type:"s",label:1,R:""}}return p4};var q4=function(){if(!r4){var a=[];r4={ka:-1,ma:a};a[1]={type:"e",label:1,R:0};a[2]={type:"s",label:1,R:""}}return r4};
var s4=function(){if(!t4){var a=[];t4={ka:-1,ma:a};a[1]={type:"e",label:3};if(!u4){var b=[];u4={ka:-1,ma:b};b[1]={type:"e",label:1,R:0};b[2]={type:"s",label:1,R:""};b[4]={type:"j",label:1,R:""}}a[2]={type:"m",label:3,$:u4};a[3]={type:"e",label:1,R:2};v4||(b=[],v4={ka:-1,ma:b},b[1]={type:"i",label:1,R:100});a[4]={type:"m",label:1,R:_.lP,$:v4};w4||(b=[],w4={ka:-1,ma:b},b[1]={type:"e",label:1,R:0});a[5]={type:"m",label:3,$:w4};x4||(b=[],x4={ka:-1,ma:b},b[1]={type:"e",label:1,R:0});a[6]={type:"m",label:3,
$:x4};y4||(b=[],y4={ka:-1,ma:b},b[1]={type:"e",label:1,R:1},b[2]={type:"e",label:1,R:1});a[8]={type:"m",label:3,$:y4}}return t4};
var z4=function(){if(!A4){var a=[];A4={ka:-1,ma:a};a[1]={type:"s",label:1,R:""};a[5]={type:"s",label:1,R:""};a[2]={type:"e",label:1,R:1};a[3]={type:"j",label:1,R:""};a[4]={type:"e",label:1,R:0};if(!B4){var b=[];B4={ka:-1,ma:b};b[1]={type:"b",label:1,R:!1}}a[6]={type:"m",label:1,R:_.ZO,$:B4};a[7]={type:"e",label:1,R:2};if(!C4){b=[];C4={ka:-1,ma:b};if(!D4){var c=[];D4={ka:-1,ma:c};c[1]={type:"b",label:1,R:!1};c[2]={type:"b",label:1,R:!1}}b[1]={type:"m",label:1,R:_.YO,$:D4}}a[8]={type:"m",label:1,R:_.$O,
$:C4};a[9]={type:"s",label:1,R:""};E4||(b=[],E4={ka:-1,ma:b},b[1]={type:"b",label:1,R:!0},b[2]={type:"b",label:1,R:!0},b[3]={type:"b",label:1,R:!0},b[4]={type:"b",label:1,R:!0},b[5]={type:"b",label:1,R:!1},b[6]={type:"s",label:3});a[10]={type:"m",label:1,R:_.aP,$:E4};F4||(b=[],F4={ka:-1,ma:b},G4||(c=[],G4={ka:-1,ma:c},c[1]={type:"b",label:1,R:!1}),b[1]={type:"m",label:1,R:_.LO,$:G4});a[11]={type:"m",label:1,R:_.bP,$:F4};H4||(b=[],H4={ka:-1,ma:b},b[2]={type:"b",label:1,R:!1},b[3]={type:"b",label:1,
R:!1});a[12]={type:"m",label:1,R:_.cP,$:H4};a[13]={type:"m",label:1,R:_.dP,$:_.Xn()};I4||(b=[],I4={ka:-1,ma:b},b[1]={type:"e",label:1,R:0},b[2]={type:"s",label:1,R:""});a[14]={type:"m",label:1,R:_.eP,$:I4}}return A4};var J4=function(a){this.N=a||[]};var zca=function(a){a.N[0]=a.N[0]||[];return new _.sM(a.N[0])};var K4=function(){return(_.Nc("Chrome")||_.Nc("CriOS"))&&!_.Oc()&&!_.Nc("Edge")};var Aca=function(a,b){this.j=[0,0,0];this.O=1/(a/(2*Math.PI));this.P=1/(b/Math.PI)};
var L4=function(a){this.N=a||[]};var f5=function(a){this.N=a||[]};
var Bca=function(a){var b=new _.ps;if(!g5){var c=[];g5={ka:-1,ma:c};c[1]={type:"m",label:1,R:_.tP,$:z4()};if(!h5){var d=[];h5={ka:-1,ma:d};d[1]={type:"m",label:1,R:_.vO,$:m4()};d[2]={type:"d",label:1,R:0};if(!i5){var e=[];i5={ka:-1,ma:e};e[1]={type:"v",label:1,R:""};e[2]={type:"f",label:1,R:0};e[3]={type:"m",label:1,R:_.kO,$:k4()};e[4]={type:"m",label:1,R:_.lO,$:k4()}}d[3]={type:"m",label:1,R:_.wO,$:i5};d[4]={type:"m",label:3,$:_.tm()};d[5]={type:"m",label:1,R:_.xO,$:m4()}}c[2]={type:"m",label:1,
R:_.uP,$:h5};c[5]={type:"m",label:1,R:_.vP,$:q4()};if(!j5){d=[];j5={ka:-1,ma:d};if(!k5){e=[];k5={ka:-1,ma:e};if(!l5){var f=[];l5={ka:-1,ma:f};f[1]={type:"e",label:3}}e[1]={type:"m",label:1,R:_.MO,$:l5};e[2]={type:"b",label:1,R:!1};e[3]={type:"b",label:1,R:!1};e[5]={type:"b",label:1,R:!1};e[6]={type:"b",label:1,R:!1}}d[1]={type:"m",label:1,R:_.OO,$:k5};m5||(e=[],m5={ka:-1,ma:e},e[1]={type:"e",label:3});d[13]={type:"m",label:1,R:_.PO,$:m5};d[2]={type:"m",label:1,R:_.QO,$:o4()};if(!n5){e=[];n5={ka:-1,
ma:e};if(!o5){f=[];o5={ka:-1,ma:f};f[1]={type:"m",label:3,$:g4()};if(!p5){var g=[];p5={ka:-1,ma:g};g[1]={type:"m",label:1,R:_.NO,$:g4()};g[2]={type:"s",label:1,R:""}}f[3]={type:"m",label:3,$:p5};f[2]={type:"b",label:1,R:!1}}e[2]={type:"m",label:1,R:_.XO,$:o5}}d[3]={type:"m",label:1,R:_.RO,$:n5};q5||(e=[],q5={ka:-1,ma:e},e[1]={type:"i",label:1,R:0},e[3]={type:"i",label:1,R:100},e[2]={type:"s",label:1,R:""});d[4]={type:"m",label:1,R:_.SO,$:q5};r5||(e=[],r5={ka:-1,ma:e},s5||(f=[],s5={ka:-1,ma:f},f[1]=
{type:"e",label:1,R:0},f[2]={type:"b",label:1,R:!1},f[3]={type:"e",label:1,R:0},f[4]={type:"e",label:1,R:0}),e[1]={type:"m",label:3,$:s5},e[2]={type:"b",label:1,R:!1},e[3]={type:"m",label:1,R:_.yO,$:g4()},e[4]={type:"b",label:1,R:!1});d[11]={type:"m",label:1,R:_.TO,$:r5};t5||(e=[],t5={ka:-1,ma:e},e[1]={type:"e",label:1,R:1},e[2]={type:"d",label:1,R:6},e[3]={type:"d",label:1,R:2},e[4]={type:"d",label:1,R:.04});d[9]={type:"m",label:1,R:_.UO,$:t5};d[10]={type:"b",label:1,R:!1};u5||(e=[],u5={ka:-1,ma:e},
e[1]={type:"e",label:1,R:1},e[2]={type:"b",label:1,R:!1});d[12]={type:"m",label:1,R:_.VO,$:u5};d[14]={type:"b",label:1,R:!1};d[8]={type:"m",label:1,R:_.WO,$:_.qm()}}c[3]={type:"m",label:1,R:_.wP,$:j5};c[4]={type:"m",label:1,R:_.xP,$:s4()};v5||(v5={ka:-1,ma:[]});c[6]={type:"m",label:1,R:_.yP,$:v5}}return b.j(a.N,g5)};var w5=function(a){a.N[1]=a.N[1]||[];return new _.EM(a.N[1])};var x5=function(a){a.N[2]=a.N[2]||[];return new _.NM(a.N[2])};var y5=function(a){this.N=a||[]};
var z5=function(a){this.N=a||[]};
var Cca=function(a){var b=new _.ps;if(!A5){var c=[];A5={ka:-1,ma:c};c[1]={type:"m",label:1,R:_.fP,$:z4()};c[2]={type:"m",label:1,R:_.gP,$:o4()};if(!B5){var d=[];B5={ka:-1,ma:d};d[1]={type:"m",label:1,R:_.jP,$:q4()};if(!C5){var e=[];C5={ka:-1,ma:e};e[1]={type:"m",label:1,R:_.eO,$:_.tm()};e[5]={type:"s",label:1,R:""};if(!D5){var f=[];D5={ka:-1,ma:f};f[1]={type:"m",label:3,$:i4()};f[2]={type:"m",label:3,$:_.tm()};f[3]={type:"m",label:3,$:_.tm()};f[4]={type:"m",label:1,R:_.dO,$:i4()};f[5]={type:"b",label:1,
R:!1};f[6]={type:"i",label:1,R:0}}e[4]={type:"m",label:1,R:_.fO,$:D5};e[6]={type:"s",label:1,R:""};e[2]={type:"s",label:1,R:""};e[3]={type:"v",label:1,R:""}}d[2]={type:"m",label:1,R:_.kP,$:C5}}c[3]={type:"m",label:3,$:B5};c[4]={type:"m",label:1,R:_.hP,$:s4()}}return b.j(a.N,A5)};var Dca=function(a){var b=[];_.Q(a.N,2).push(b);return new J4(b)};
var E5=function(a){for(var b=[],c=0,d=a.length;c<d;++c)for(var e=a[c],f=0,g=e.length;f<g;f+=2)b.push(f?"L":"M"),b.push(Math.round(10*e[f])/10,Math.round(10*e[f+1])/10);return b.join(" ")};var Eca=function(a,b){if(!a||!b)return 0;var c=_.A(b.lat()-a.lat()),d=_.A(b.lng()-a.lng()),c=Math.sin(c/2)*Math.sin(c/2)+Math.cos(_.A(a.lat()))*Math.cos(_.A(b.lat()))*Math.sin(d/2)*Math.sin(d/2);return 2*Math.atan2(Math.sqrt(c),Math.sqrt(1-c))};
var Fca=function(a){this.P=a;this.j=_.xg;var b=this.O=Array(Math.max(16,22));F5(a,0,8,b);a=b[7];if(8==b[0]&&8==a){var c=b[3]|b[4]<<8,b=b[5]|b[6]<<8;this.j=new _.O(c,b);this.S=a;this.T=a+b*c}};var Gca=function(a,b){this.O=_.xg;var c=this.j=Array(16);this.na=Array(4);F5(a,0,8,c);var d=c[7];if(8==c[0]&&8==d){this.S=a;this.P=b;var e=c[3]|c[4]<<8,c=c[5]|c[6]<<8;this.O=new _.O(e,c);this.T=d;this.U=d+c*e;this.V=new Aca(e,c)}};
var Hca=function(){for(var a=this.j=Array(256),b=0;256>b;++b)a[b]=Math.pow(2,b-150)};var G5=function(a,b,c){return 0==(b[c+3]&127|b[c+2]|b[c+1]|b[c])?0:(1-((b[c+3]&128)>>6))*((b[c+2]|128)<<16|b[c+1]<<8|b[c])*a.j[(b[c+3]&127)<<1|(b[c+2]&128)>>7]};var H5=function(){this.j="";this.O=Array(128);for(var a=0;65>a;a++)this.O["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charCodeAt(a)]=a};var I5=function(a,b){var c=b.length%4;c&&(b+="A..".substr(c-1));a.j=b};
var F5=function(a,b,c,d){if(0!=c){var e=4*Math.floor(b/3);b%=3;for(var f=0,g,h,k,n=0;f<c;){g=a.O[a.j.charCodeAt(e++)];h=a.O[a.j.charCodeAt(e++)];k=a.O[a.j.charCodeAt(e++)];n=a.O[a.j.charCodeAt(e++)];if(0==b&&(d[f++]=g<<2|h>>4,f>=c))break;if(1>=b&&(d[f++]=h<<4&240|k>>2,f>=c))break;d[f++]=k<<6&192|n;b=0}}};var Ica=function(a,b){var c=0;_.kc(a,function(d,e){c=b.call(void 0,c,d,e,a)});return c};
var Jca=function(a){function b(a,e){for(var f=0;f<e.length;f++){var g=e.splice(f,1);0==e.length?c.push(a.concat(g)):(b(a.concat(g),e.slice()),e.splice(f,0,g[0]))}return c}var c=[];return b([],a)};var J5=function(a){_.ik("\u4e0d\u518d\u63d0\u4f9b\u8be5\u56fe\u7247",a);a.style.color="white";a.style.fontFamily="Roboto,Arial,sans-serif";a.style.backgroundColor="black";a.style.padding=_.V(4);a.style.border=_.V(2)+" solid white";_.rk(a);_.MB(a);this.j=a};
var K5=function(a){a=this.j=_.X("div",a);a.style.padding="5px";try{a.style.backgroundColor="rgba(255,255,255,.75)"}catch(b){a.style.backgroundColor="#ebebeb"}a.style.fontFamily="Roboto,Arial,sans-serif";a.style.fontSize=_.V(11);a.style.color="#222";this.O=_.ik("",a);a=_.X("div",a);a.style.fontSize="10px";a.style.color="#666";_.ik("\u5730\u5740\u4e3a\u5927\u81f4\u4fe1\u606f",a)};var L5=function(){this.O=new _.Tu(10);this.j=0;this.S=null};
var M5=function(a){var b=this,c=this.P=_.X("div",a,_.tg,null,!1,{title:"\u9000\u51fa\u8857\u666f"});_.qk(c,2);a=this.T=_.X("div",a);_.qk(a,1);a.style.fontSize="1px";a.style.backgroundColor="#BBBBBB";this.O=_.mJ().buttons;this.S=_.rJ(c,b.O,0);this.j=_.rJ(c,b.O,1);this.changed();_.BC(b.j,!1);_.I.addDomListener(b.S,"mouseover",function(){_.BC(b.j,!0);_.BC(b.S,!1)});_.I.addDomListener(b.j,"mouseout",function(){_.BC(b.S,!0);_.BC(b.j,!1)});c=(0,_.t)(_.I.trigger,null,this,"closeclick");_.I.addDomListener(b.P,
"click",c)};var N5=function(a,b,c){this.Ba=[];this.O=a;this.S=b;a=this.P=_.X("div",c,_.tg);this.j="";a=_.X("div",a,_.tg,Kca);Lca(this,a,b.pano)};var Lca=function(a,b,c){c&&(b.setAttribute("pano",c),b.setAttribute("cursor","pointer"),a.Ba.push(_.I.addDomListener(b,"mouseover",function(){a.j="#CCFFFF";_.I.trigger(a,"forceredraw");a.set("hovering",!0)}),_.I.addDomListener(b,"mouseout",function(){a.j="";_.I.trigger(a,"forceredraw");a.set("hovering",!1)})))};
var O5=function(a,b){this.Ba=[];var c=E5([P5]),d=E5([Q5]);this.T=b.heading;this.S=R5(a,d,"black",.5);this.O=R5(a,d,"white",1);this.P=R5(a,c,"white",0);S5(this,this.P,b.pano,this.O);b.description&&(c=b.description,d=T5(a,"text","white"),d.setAttribute("x",0),d.setAttribute("y",-140),d.setAttribute("font-size","20px"),d.setAttribute("text-anchor","middle"),d.appendChild(_.gk(a).createTextNode(c)),this.j=d,S5(this,this.j,b.pano,this.j))};
var R5=function(a,b,c,d){c=T5(a,"path",c,d);null!=b&&c.setAttribute("d",b);a.appendChild(c);return c};var T5=function(a,b,c,d){b=_.gk(a).createElementNS("http://www.w3.org/2000/svg",b);c&&(b.setAttribute("fill",c),b.setAttribute("fill-rule","evenodd"),_.C(d)&&b.setAttribute("fill-opacity",d));b.setAttribute("stroke","none");a.appendChild(b);return b};
var S5=function(a,b,c,d){c&&(b.setAttribute("pano",c),b.setAttribute("cursor","pointer"),a.Ba.push(_.I.addDomListener(b,"mouseover",function(){d.setAttribute("fill","#CCFFFF");a.set("hovering",!0)}),_.I.addDomListener(b,"mouseout",function(){d.setAttribute("fill","white");a.set("hovering",!1)})))};var U5=function(a,b,c,d,e,f,g,h){a.setAttribute("transform","translate("+c+" "+d+") "+(1!=e?"scale(1 "+e+") ":"")+(b?"rotate("+b+") ":"")+(f?"rotate("+f+" "+g+" "+h+")":""))};
var V5=function(a,b){this.Ba=[];this.T=b.heading;var c=P5.join(" "),d=Q5.join(" "),e=this.U=_.AD("polyline",a,{stroked:!1,points:d});_.kk(e,{left:0,top:0,"z-index":1});_.AD("fill",e,{color:"black",opacity:.5});this.oa=_.AD("skew",e,{on:!0,origin:"0,1.5",matrix:"1,0,0,1,0,0"});e=this.S=_.AD("polyline",a,{stroked:!1,points:d});_.kk(e,{left:0,top:_.V(-3),"z-index":2});d=_.AD("fill",e,{color:"white",opacity:1});this.na=_.AD("skew",e,{on:!0,origin:"0,1.5",matrix:"1,0,0,1,0,0"});c=this.V=_.AD("polyline",
a,{stroked:!1,points:c});_.AD("fill",c,{color:"white",opacity:0});this.qa=_.AD("skew",c,{on:!0,origin:"0,"+5/6,matrix:"1,0,0,1,0,0"});W5(this,c,b.pano,d);b.description&&(c=this.O=_.AD("line",a,{stroked:!1,from:"-10,-140",to:"10,-140"}),_.kk(c,{height:_.V(20)}),d=_.AD("fill",c,{on:!0,color:"white",opacity:1}),this.P=_.AD("skew",c,{on:!0,origin:"0,7",matrix:"1,0,0,1,0,0"}),_.AD("path",c,{textpathok:!0}),e=this.j=_.AD("textpath",c,{on:!0,string:b.description}),_.kk(e,{"font-size":"20px","font-family":"Roboto,Arial,sans-serif"}),
W5(this,c,b.pano,d))};var W5=function(a,b,c,d){c&&(b.setAttribute("pano",c),b.setAttribute("cursor","pointer"),a.Ba.push(_.I.addDomListener(b,"mouseover",function(){d.setAttribute("color","#CCFFFF");a.set("hovering",!0)}),_.I.addDomListener(b,"mouseout",function(){d.setAttribute("color","white");a.set("hovering",!1)})))};
var X5=function(a,b,c,d,e,f,g){f=f||0;g=g||0;var h=_.A(b),k=Math.cos(h)+1-1,h=Math.sin(h)+1-1;e=_.A(b+(e||0));b=Math.cos(e)+1-1;e=Math.sin(e)+1-1;a.matrix=[Number(b).toFixed(4),Number(-e).toFixed(4),Number(e*d).toFixed(4),Number(b*d).toFixed(4),0,0].join();a.offset=Math.round(50*(0+((k-b)*f-(h-e)*g)))/1E3+","+Math.round(50*(c+((h-e)*f+(k-b)*g)))/1E3};
var Y5=function(a){_.S.call(this);this.O=a;this.O.style.fontFamily="Roboto,Arial,sans-serif";this.P=[];this.T=_.I.addDomListener(a,"click",(0,_.t)(this.pp,this));this.V=_.I.addDomListener(this,"keydown",(0,_.t)(this.hm,this));this.j=null;this.S=!1;this.set("hovering",!1)};var Mca=function(a){var b=a.j&&a.j.context;b&&b.clearRect(0,0,a.j.width,a.j.height)};var Z5=function(a){_.G(a.P,function(a){_.G(a.Ba,_.I.removeListener);a.Ba.length=0;a.release()});a.P.length=0};
var Nca=function(a){var b=a.j;if(b){var c;_.pC()?c=O5:_.JB()?c=N5:_.CD()&&(c=V5);var d=a.O;_.G(a.get("links"),function(e){e=new c(b,e,d);e.Ba=[_.I.forward(e,"forceredraw",a),_.I.addListener(e,"hovering_changed",function(){a.set("hovering",this.get("hovering"))})];a.P.push(e)})}};
var $5=function(a){var b=a.get("size"),c=a.get("pov");if(b&&c&&_.C(c.pitch)){var c=c.pitch,d=1;-30<c&&(d=80>c- -30?d+Math.tan(_.A(c- -30)):d+6);a.set("center",new _.N(b.width/2,b.height/2*d));a.set("yScale",-Math.sin(_.A(Math.min(c,-30)))/d)}};
var Oca=function(a){a6(a,"addressControl","Sac");a6(a,"clickToGo","Scg");a6(a,"disableDefaultUI","Sdd");a6(a,"disableDoubleClickZoom","Sdc");a6(a,"enableCloseButton","Scb");a6(a,"imageDateControl","Sid");a6(a,"linksControl","Slc");a6(a,"panControl","Spc");a6(a,"scrollwheel","Scw");a6(a,"zoomControl","Szc");b6(a,"addressControlOptions","Sap");b6(a,"panControlOptions","Spp");b6(a,"zoomControlOptions","Szp")};
var Pca=function(a){switch(a){case 11:return"-bc";case 10:return"-bl";case 12:return"-br";case 6:return"-lb";case 4:return"-lc";case 5:return"-lt";case 9:return"-rb";case 8:return"-rc";case 7:return"-rt";case 2:return"-tc";case 13:return"-c";case 3:return"-tr"}return"-tl"};var a6=function(a,b,c){function d(){var d=a.get(b);d?_.Y(a,c,"-y"):0==d&&_.Y(a,c,"-n")}_.I.addListener(a,b.toLowerCase()+"_changed",d);d()};
var b6=function(a,b,c){function d(){var d=a.get(b);d&&d.position&&_.Y(a,c,Pca(d.position))}_.I.addListener(a,b.toLowerCase()+"_changed",d);d()};var c6=function(a){this.j=a;this.pa=null};var d6=function(){this.j=new _.N(0,0);this.O=!1};
var e6=function(a){var b=_.tJ(a,_.of(a)),c=_.gk(a).createElementNS("http://www.w3.org/2000/svg","ellipse");this.O=c;c.setAttribute("fill","white");c.setAttribute("fill-rule","evenodd");c.setAttribute("visibility","hidden");b.appendChild(c);a=_.gk(a).createElementNS("http://www.w3.org/2000/svg","path");a.setAttribute("fill","white");a.setAttribute("fill-rule","evenodd");a.setAttribute("visibility","hidden");b.appendChild(a);this.P=a;this.j=c};
var f6=function(a){var b=_.of(a);a=_.AD("group",a);_.nf(a,b);_.hk(a,_.tg);a.coordsize=b.width+" "+b.height;b=this.P=_.AD("oval",a,{});_.kk(b,{left:_.V(-50),top:_.V(-50),width:_.V(100),height:_.V(100),"z-index":1});this.j=this.O=_.AD("fill",b,{color:"white",on:!1});_.AD("stroke",b,{on:!1});b=this.S=_.AD("polyline",a,{points:"-75 -40 -75 40 75 40 75 -40"});_.kk(b,{left:_.V(0),top:_.V(0),"z-index":1});_.AD("stroke",b,{opacity:0});this.T=_.AD("fill",b,{color:"white",on:!1})};
var g6=function(a,b,c){this.V=new L5;this.V.bindTo("pov",this);this.na=a;this.Aa=b;this.Ea=c;this.P="";var d;_.pC()?d=e6:_.CD()&&(d=f6);this.j=new d(a);this.Ka=new _.N(0,0);this.qa=this.oa=0;this.U=this.S=this.ta=this.T=null;this.O=[new _.N(0,0),new _.N(0,0)]};
var h6=function(a,b){if(!a.get("linksHovering")){var c=a.get("pov"),d=a.get("worldSize"),e=a.get("depthMap"),f=a.get("projection"),g=e&&e.O;if(c&&d&&e&&f&&!g.j(_.xg)){a.T=c;var h=_.Ia(a.get("headingOffset"),0,360),k=a.get("size"),n=f.Lf(b,k,d,c,h),p=a.Ka;p.x=n.x;p.y=n.y;p.x/=d.width;p.y/=d.height;var d=p.x*g.width,q=p.y*g.height,g=e.na;if(e.O==_.xg)n=0;else{var n=Math.floor(d+.5),r=Math.floor(q+.5),n=_.Ia(n,0,e.O.width),r=_.Ia(r,0,e.O.height);F5(e.S,e.T+r*e.O.width+n,1,e.j);n=e.j[0]}if(0==n)g[0]=
0;else{var r=e.V,v=(q+.5)*r.P,q=Math.sin(v),v=Math.cos(v),d=1.5*Math.PI-d*r.O,x=Math.sin(d);r.j[0]=q*Math.cos(d);r.j[1]=q*x;r.j[2]=v;d=r.j;F5(e.S,e.U+16*n,16,e.j);n=G5(e.P,e.j,0);r=G5(e.P,e.j,4);q=G5(e.P,e.j,8);e=G5(e.P,e.j,12);g[1]=n;g[2]=r;g[3]=q;g[0]=_.Ha(e/(d[0]*n+d[1]*r+d[2]*q),3,500)}if(0==g[0])a.j.set("visible",!1);else{a.j.set("visible",!0);k=.7*k.width*Math.pow(2,c.zoom)/g[0];.9<Math.abs(g[3])?(h=k,c=c.pitch,f=0<g[3]?1:-1,g=g[0],a.j.set("shape",0),h*=.8,c=Math.sin(_.A(Math.max(10,f*c*Math.min(1,
Math.asin(3/g))))),a.O[0].x=Math.round(b.x-h),a.O[0].y=Math.round(b.y-h*c),a.O[1].x=Math.round(b.x+h),a.O[1].y=Math.round(b.y+h*c),a.j.set("pancakePoints",a.O)):(a.j.set("shape",1),e=_.Ka(Math.abs(Math.atan2(g[2],g[1]))),d=a.get("size"),n=a.get("worldSize"),c=f.Ei(b,p,k,Qca,e,c,d,n,h),a.j.set("wafflePoints",c),a.oa=g[0],a.qa=_.Ia(360*p.x-h,0,360));g=(c=a.get("panoMap"))&&c.j;a.P="";if(c&&!_.xg.j(g)){c.j==_.xg?p=0:(h=Math.floor(p.x*g.width+.5),p=Math.floor(p.y*g.height+.5),h=_.Ia(h,0,c.j.width),p=
_.Ia(p,0,c.j.height),F5(c.P,c.S+p*c.j.width+h,1,c.O),p=c.O[0]);if(p)for(F5(c.P,c.T+22*(p-1),22,c.O),p="",h=0;22>h;h++)p+=String.fromCharCode(c.O[h]);else p="";p!=a.get("pano")&&(a.P=p)}a.j.set("opacity",a.P?.5:.2)}}else a.ud()}};var wca=function(a){var b=[];_.Fa(a,function(a,d){var e=[d];_.Ua(d)&&(e=d);_.G(e,function(d){null!=d&&b.push((0,window.encodeURIComponent)(a)+"="+(0,window.encodeURIComponent)(d))})});return b.join("&")};
var i6=function(a){_.S.call(this);this.S=100;this.j=this.O=0;this.N=[];this.Jb=a};var j6=function(){this.j=this.S=this.P=this.O=0};var k6=function(a,b,c,d,e){this.rn=a;this.P=b;this.Kf=c;this.Ue=d;this.Of=[null,null,null,null];this.Gf=-1;this.ih=0;this.Gc=this.jb=null;this.Eh=this.j=!1;this.O=null;a=1/e;this.O=new window.Float32Array([a,0,0,0,0,a,0,0,0,0,1,0,-this.Ue,-this.Kf,0,1])};
var l6=function(a,b){a.Gc=b.createTexture();b.bindTexture(b.TEXTURE_2D,a.Gc);b.texImage2D(b.TEXTURE_2D,0,b.RGBA,b.RGBA,b.UNSIGNED_BYTE,a.jb);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MAG_FILTER,b.LINEAR);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_MIN_FILTER,b.LINEAR);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_WRAP_S,b.CLAMP_TO_EDGE);b.texParameteri(b.TEXTURE_2D,b.TEXTURE_WRAP_T,b.CLAMP_TO_EDGE);b.bindTexture(b.TEXTURE_2D,null);a.jb=null;a.Eh=!0};
var m6=function(a,b,c,d,e){this.S=c;this.P=d;this.j=e;this.O=Array(d*e);a=Math.pow(2,a-c);for(var f=0,g=0;f<d;++f)for(var h=0;h<e;++h){var k=b(f,h,a);this.O[g++]=new k6(k,c,f,h,a)}};var n6=function(){this.O=[];this.qa=[];this.P=[]};var o6=function(a,b){if(!b.j){b.j=!0;var c=a.V.getTileUrl(a.V.id,b.getZoom(),b.Ue,b.Kf);if(c){var d=b.jb=new window.Image;d.onload=(0,_.t)(a.Qq,a,b,!0);d.onerror=(0,_.t)(a.tk,a,b);d.crossOrigin="";d.src=c}else a.tk(b)}};
var Rca=function(a,b){this.j=a;this.Aa=[];this.na=[];this.P=[];this.oa=[];this.T=[];this.S=[];var c=b.U,d=b.T,e=Math.pow(2,6-b.j),f=[],g=[],h=[];this.qa=b.ta*c;this.ta=b.oa*d;p6(this);var k=[],n=[],p=1/this.qa;k.push(.5*Math.PI);var q,r;for(r=1;r<c;++r)q=Math.PI*(.5-p*r),k.push(q);k.push(.5*-Math.PI);c=1/this.ta;n.push(Math.PI);for(r=1;r<d;++r)q=2*Math.PI*(.5-c*r),n.push(q);n.push(-Math.PI);var c=1/e,v,x;r=0;for(d=k.length-1;r<d;++r)for(v=k[r],x=k[r+1],p=0;p<e;++p)q=v+p*c*(x-v),this.Aa.push(q),this.na.push(Math.sin(q)),
this.P.push(Math.cos(q));0<k.length&&(this.Aa.push(x),this.na.push(Math.sin(x)),this.P.push(Math.cos(x)));r=0;for(d=n.length-1;r<d;++r)for(k=n[r],x=n[r+1],x=x-k,p=0;p<e;++p)q=k+p*c*x,this.oa.push(q),this.T.push(Math.sin(q)),this.S.push(Math.cos(q));0<n.length&&(this.oa.push(this.oa[0]),this.T.push(this.T[0]),this.S.push(this.S[0]));n=b.U;r=b.T;k=0;x=(e+1)*(e+1);for(d=[b.S];0<d.length;)if(c=d.pop(),0<=c.Gf)c.ih=k-c.Gf;else if(c.Gf=k,c.getZoom()==b.j){c.ih=1;var w=c.Kf,z=c.Ue,c=e;q=k*x;var F=f,D=g,
p=h,E=1,H=1;this.ta<z+1&&(E=this.ta-(r-1));this.qa<w+1&&(H=this.qa-(n-1));var P=w*c,U=z*c,Z=1/c,oa=v=void 0,Ya=c+1;for(v=0;v<Ya;++v)for(oa=0;oa<Ya;++oa)F.push(this.P[P+v]*this.T[U+oa],this.na[P+v],this.P[P+v]*this.S[U+oa]),D.push(0+(E-0)*oa*Z+z,0+(H-0)*v*Z+w);for(v=0;v<c;++v)for(oa=0;oa<c;++oa)w=q+Ya*v+oa,z=w+1,F=w+Ya,p.push(w,z,F,F,z,F+1);++k}else for(d.push(c),q=3;0<=q;--q)c.Of[q]&&d.push(c.Of[q]);p6(this);this.Ea=e*e*6;e=this.j;this.U=e.createBuffer();e.bindBuffer(e.ARRAY_BUFFER,this.U);e.bufferData(e.ARRAY_BUFFER,
new window.Float32Array(g),e.STATIC_DRAW);this.V=e.createBuffer();e.bindBuffer(e.ARRAY_BUFFER,this.V);e.bufferData(e.ARRAY_BUFFER,new window.Float32Array(f),e.STATIC_DRAW);this.O=e.createBuffer();e.bindBuffer(e.ELEMENT_ARRAY_BUFFER,this.O);e.bufferData(e.ELEMENT_ARRAY_BUFFER,new window.Uint16Array(h),e.STATIC_DRAW);e.enableVertexAttribArray(0);e.enableVertexAttribArray(1);e.bindBuffer(e.ARRAY_BUFFER,this.V);e.vertexAttribPointer(1,3,e.FLOAT,!1,0,0);e.bindBuffer(e.ARRAY_BUFFER,this.U);e.vertexAttribPointer(0,
2,e.FLOAT,!1,0,0);e.bindBuffer(e.ELEMENT_ARRAY_BUFFER,this.O)};var p6=function(a){a.Aa=[];a.na=[];a.P=[];a.oa=[];a.T=[];a.S=[]};var q6=function(){this.m=Array(16)};var r6=function(a){a.m=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]};var s6=function(a,b){for(var c=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],d=0;4>d;d++)for(var e=0;4>e;e++)for(var f=0;4>f;f++)c[4*d+e]+=a.m[f+4*d]*b.m[4*f+e];a.m=c};var Sca=function(a){for(var b=Array(16),c=0;16>c;c++)b[c]=a.m[c];return b};
var t6=function(){this.Aa=new j6;this.S=new q6;this.P=this.na=null;this.V=60};var u6=function(a,b,c){b=a.j.createShader(b);if(!b)return null;a.j.shaderSource(b,c);a.j.compileShader(b);return a.j.getShaderParameter(b,a.j.COMPILE_STATUS)?b:(a.j.deleteShader(b),null)};
var Tca=function(a){var b=u6(a,a.j.VERTEX_SHADER,"uniform mat4 u_modelViewProjMatrix;uniform mat4 u_texTransMatrix;attribute vec4 vTexCoord;attribute vec4 vPosition;varying vec2 v_texCoord;void main(){    gl_Position = u_modelViewProjMatrix * vPosition;    vec4 transTexCoord = u_texTransMatrix * vTexCoord;    v_texCoord = transTexCoord.st;}"),c=u6(a,a.j.FRAGMENT_SHADER,"#ifdef GL_ES\nprecision highp float;\n#endif\nuniform sampler2D sampler2d;varying vec2 v_texCoord;void main(){    gl_FragColor = texture2D(sampler2d,v_texCoord);}");
if(!b||!c)return!1;a.P=a.j.createProgram();if(!a.P)return!1;a.j.attachShader(a.P,b);a.j.attachShader(a.P,c);a.j.bindAttribLocation(a.P,0,"vTexCoord");a.j.bindAttribLocation(a.P,1,"vPosition");a.j.linkProgram(a.P);if(!a.j.getProgramParameter(a.P,a.j.LINK_STATUS))return a.j.deleteProgram(a.P),a.j.deleteShader(c),a.j.deleteShader(b),!1;a.j.useProgram(a.P);a.j.uniform1i(a.j.getUniformLocation(a.P,"sampler2d"),0);return!0};
var v6=function(a,b){if(b.clientWidth!=a.U||b.clientHeight!=a.T)a.U=b.clientWidth,a.T=b.clientHeight,a.j.viewport(0,0,a.U,a.T),a.na=new q6,w6(a)};var w6=function(a){if(a.j&&a.na){var b=a.na,c=a.U/a.T;a=1*Math.tan(1*Math.atan(Math.tan(.5*_.A(a.V))/(a.U/a.T)));var d=-a,e=c*d,c=c*a,f=(c+e)/(c-e),g=(a+d)/(a-d),h=-10001/9999;r6(b);b.m[0]=2/(c-e);b.m[5]=2/(a-d);b.m[8]=f;b.m[9]=g;b.m[10]=h;b.m[11]=-1;b.m[14]=-2.000200020002}};var x6=function(a){this.j=new _.Yf;this.j.Jb=a};
var y6=function(a,b,c){_.S.call(this);this.Jb=b;this.P=new _.O(512,512);this.Ka=0;this.Aa=null;this.qa=!1;this.ta=null;this.set("projection",c);this.S=a;a.style.width="100%";a.style.height="100%";this.oi();_.I.bind(this,"movestart",this,this.km);_.I.bind(this,"move",this,this.lm);_.I.bind(this,"moveend",this,this.jm);_.I.bind(this,"resize",this,this.oi);this.na=new x6(b);this.na.bindTo("result",this,null,!0);this.bindTo("status",this.na,"status",!0)};
var z6=function(a){var b=a.get("result");if(b){var c=b.copyright||"";if(a.get("imageDateControl")){var d;a:{if(d=b.imageDate){var e=d.split("-");if(!(1>e.length)){d=e[0];var f="";1<e.length&&(e=_.Gj(e[1])-1,0<=e&&12>e&&(f=Uca[e]));d="\u56fe\u7247\u65e5\u671f\uff1a"+(d+(" \u5e74 "+f));break a}}d=void 0}d&&(c&&(c+=" - "),c+=d)}a.set("copyright",c);a.set("depthMap",b.zn);a.set("disabled",b.disabled);a.set("floorId",b.ce);a.set("floors",b.bj);a.set("panoMap",b.Np);a.set("scene",b.rh);a.set("takeDownUrl",
b.takeDownUrl)}};var A6=function(a,b){var c=a.get("size"),d=a.get("zoom"),e=a.Ka,f=a.Xa;f&&c&&_.C(d)&&_.C(e)&&(c=_.Ha(Math.ceil(_.fj(c.width/(.25*Math.pow(2,1-d))/a.P.width)),0,e),d=a.get("tileZoom"),c!=d||b)&&(e=Math.pow(2,c-e),a.set("worldSize",new _.O(Math.round(f.width*e),Math.round(f.height*e))),a.set("tileZoom",c))};var B6=function(){this.O=new _.N(0,0);this.P=new _.N(0,0);this.j=[];for(var a=0;4>a;a++)this.j.push(new _.N(0,0))};
var C6=function(a,b,c,d,e,f){a=a.P;var g=e.pitch/180*Math.PI;f=_.Ia(_.A(e.heading+f),0,2*Math.PI);var h=Math.cos(g),g=Math.sin(g),k=c.width/2;c=c.height/2;var n=2*Math.PI*b.x/d.width;b=Math.PI*(.5-b.y/d.height);e=k*Math.pow(2,e.zoom-1)/(h*Math.cos(b)*Math.cos(f-n)+g*Math.sin(b));a.x=k-e*Math.cos(b)*Math.sin(f-n);a.y=c-e*(h*Math.sin(b)-g*Math.cos(b)*Math.cos(f-n));return a};var D6=function(a,b){y6.call(this,a,b,new B6);this.V=_.X("canvas",a);this.T=this.j=!1;this.O=null};
var E6=function(){this.O=new _.N(0,0);this.j=[];for(var a=0;4>a;a++)this.j.push(new _.N(0,0))};var F6=function(a,b){y6.call(this,a,b,new E6);this.S=a;this.O=[];this.T=null;this.kb=_.iw();this.Ea=!1;this.Oa=null};var G6=function(a){a.T&&(window.clearTimeout(a.T),a.T=null)};var H6=function(a,b,c,d,e){a=a.createElement("img");a.O=e;b.appendChild(a);_.hk(a,d);_.uB(a,c,a.O)};
var I6=function(a,b,c,d,e,f,g,h,k){this.ta=a;this.Aa=b;this.S=c;this.U=d;this.T=e;this.V=f;this.Ea=g||Math.sqrt((c-a)*(c-a)+(d-b)*(d-b));this.Ka=h||Math.sqrt((e-c)*(e-c)+(f-d)*(f-d));this.Oa=k||Math.sqrt((a-e)*(a-e)+(b-f)*(b-f))};var J6=function(a){return Math.min(a.j,a.O,a.P)};var K6=function(a){return Math.min(a.na,a.oa,a.qa)};var L6=function(a){return Math.max(a.j,a.O,a.P)};var M6=function(a){return Math.max(a.na,a.oa,a.qa)};var Vca=function(){};
var N6=function(a,b){y6.call(this,a,b,new B6);this.j=_.X("canvas",a);this.Ea=this.j.getContext("2d");this.Oa=_.kB().Pa;this.V=this.T=!1};var O6=function(a){var b=a.Hd(),c=a.P;if(b&&c){var d=Math.ceil(b.width/c.width),e=Math.ceil(b.height/c.height);a=a.O=[];for(var f=0;f<d;f++)for(var g=0;g<e;g++)a.push({wa:c.width*(f+1),ua:c.width*f,ra:c.height*g,x:f,y:g});for(g=0;g<e;g++)a.push({wa:b.width+c.width,ua:b.width,ra:c.height*g,x:0,y:g})}};
var P6=function(a,b,c){var d=c.worldSize.width,e=d/2;Wca(b,c);L6(b)-J6(b)>e&&(b.j<e&&(b.j+=d),b.O<e&&(b.O+=d),b.P<e&&(b.P+=d));var f=c.Ec,g=f.pitch/180*Math.PI,d=(f.heading+c.j)/180*Math.PI,e=Math.cos(g),g=Math.sin(g),h=c.width/2,k=c.height/2,n=c.worldSize,p=(b.j+b.O+b.P)/3*Math.PI*2/n.width,n=Math.PI*(.5-(b.na+b.oa+b.qa)/3/n.height),f=h*Math.pow(2,f.zoom-1)/(e*Math.cos(n)*Math.cos(d-p)+g*Math.sin(n));b.Xa=h-f*Math.cos(n)*Math.sin(d-p);b.kb=k-f*(e*Math.sin(n)-g*Math.cos(n)*Math.cos(d-p));9<Math.pow(b.Xa-
(b.ta+b.S+b.T)/3,2)+Math.pow(b.kb-(b.Aa+b.U+b.V)/3,2)?(P6(a,new I6(b.ta,b.Aa,(b.ta+b.S)/2,(b.Aa+b.U)/2,(b.T+b.ta)/2,(b.V+b.Aa)/2,b.Ea/2,b.Ka/2,b.Oa/2),c),P6(a,new I6(b.S,b.U,(b.S+b.T)/2,(b.U+b.V)/2,(b.ta+b.S)/2,(b.Aa+b.U)/2,b.Ka/2,b.Oa/2,b.Ea/2),c),P6(a,new I6(b.T,b.V,(b.T+b.ta)/2,(b.V+b.Aa)/2,(b.S+b.T)/2,(b.U+b.V)/2,b.Oa/2,b.Ea/2,b.Ka/2),c),P6(a,new I6((b.ta+b.S)/2,(b.Aa+b.U)/2,(b.S+b.T)/2,(b.U+b.V)/2,(b.T+b.ta)/2,(b.V+b.Aa)/2,b.Oa/2,b.Ea/2,b.Ka/2),c)):Xca(a,b,c)};
var Wca=function(a,b){function c(a,b){var c=v,d=q-b,e=g*c-h*d,f=p-a,U=k*e+n*f,c=h*c+g*d,f=k*f-n*e,e=Math.atan2(-f,U);0>e&&(e+=2*Math.PI);U=Math.atan2(c,Math.sqrt(U*U+f*f));x=e*r.width/(2*Math.PI);w=r.height*(.5-U/Math.PI)}var d=b.Ec,e=d.pitch/180*Math.PI,f=(d.heading+b.j)/180*Math.PI,g=Math.cos(e),h=Math.sin(e),k=Math.cos(f),n=Math.sin(f),p=b.width/2,q=b.height/2,r=b.worldSize,v=p*Math.pow(2,d.zoom-1),x,w;c(a.ta,a.Aa);a.j=x;a.na=w;c(a.S,a.U);a.O=x;a.oa=w;c(a.T,a.V);a.P=x;a.qa=w};
var Q6=function(a,b,c){var d=b.worldSize,e=b.tileSize,f=Math.ceil(d.height/e.height),d=Math.min(Math.floor(L6(a)/e.width),Math.ceil(d.width/e.width)),g=Math.floor(K6(a)/e.height),h=Math.floor(M6(a)/e.height);for(a=Math.floor(J6(a)/e.width);a<=d;a++)for(e=g;e<=h;e++){var k=b.P[a*f+e];k&&c(k,a)}};var Xca=function(a,b,c){var d=!1;Q6(b,c,function(e){e.tf?d||(R6(e,b,c),d=!0):(e.Rf.push(b),e.Vg||(Yca(a,e,c),e.Vg=!0))})};
var Yca=function(a,b,c){var d=new _.HA(a.getTileUrl(c.Nd,c.O,b.x,b.y));a.Oa.load(d,function(a){b.jb=a;b.Vg=!1;b.tf=!0;Zca(b,c)})};var Zca=function(a,b){_.G(a.Rf,function(c){R6(a,c,b)});a.Rf=[]};
var R6=function(a,b,c){function d(a,b,c){var d=a.ua+(a.wa<h?r.width:0);if(f){var g=h-d,D=k-a.ra,E=n-h,H=p-k,d=h,P=k;0>g&&(d-=g,E+=g,g=0);0>D&&(P-=D,H+=D,D=0);E=Math.min(E,q.width-g);H=Math.min(H,q.height-D);a=a.jb;var U,Z,E=E+4,H=H+4,d=d-2,P=P-2;U=g-2;Z=D-2;var D=E,g=H,oa=a.width/q.width,Ya=a.height/q.height;U*=oa;Z*=Ya;var E=E*oa,H=H*Ya,$a=5==_.W.type?1:0,Bb=Math.max($a,U),sc=Math.max($a,Z);U=Bb-U;Z=sc-Z;d+=U/oa;P+=Z/Ya;E+=U;H+=Z;D+=U/oa;g+=Z/Ya;U=Math.max(0,Bb+E-a.width+$a);Z=Math.max(0,sc+H-a.height+
$a);E-=U;H-=Z;0<E&&0<H&&0<a.height&&0<a.width&&e.drawImage(a,Bb,sc,E,H,d+b-1,P+c-1,D-U/oa+2,g-Z/Ya+2)}else E=e,H=a.jb,b=d+b,c=a.ra+c,a=q,0<H.height&&0<H.width&&(3==_.W.type?(d=Math.min(2,b),P=Math.min(2,c),E.drawImage(H,b-d,c-P,a.width+2+d,a.height+2+P)):E.drawImage(H,b,c,a.width,a.height))}var e=c.S;e.save();var f=3!=_.W.type;$ca(e,b.ta,b.Aa,b.S,b.U,b.T,b.V,b.Ea,b.Ka,b.Oa);var g=b.j*(b.qa-b.oa)+b.O*(b.na-b.qa)+b.P*(b.oa-b.na);e.transform((b.ta*(b.qa-b.oa)+b.S*(b.na-b.qa)+b.T*(b.oa-b.na))/g,(b.Aa*
(b.qa-b.oa)+b.U*(b.na-b.qa)+b.V*(b.oa-b.na))/g,(b.ta*(b.O-b.P)+b.S*(b.P-b.j)+b.T*(b.j-b.O))/g,(b.Aa*(b.O-b.P)+b.U*(b.P-b.j)+b.V*(b.j-b.O))/g,(b.ta*(b.P*b.oa-b.O*b.qa)+b.S*(b.j*b.qa-b.P*b.na)+b.T*(b.O*b.na-b.j*b.oa))/g,(b.Aa*(b.P*b.oa-b.O*b.qa)+b.U*(b.j*b.qa-b.P*b.na)+b.V*(b.O*b.na-b.j*b.oa))/g);var h=J6(b),k=K6(b),n=L6(b),p=M6(b),q=c.tileSize,r=c.worldSize;Math.floor(J6(b)/q.width)==Math.floor(L6(b)/q.width)&&Math.floor(K6(b)/q.height)==Math.floor(M6(b)/q.height)?d(a,0,0):(c.T||3!=_.W.type&&5!=_.W.type||
Q6(b,c,function(a){if(a.tf){var b=f?1.5:.75,c=a.ua+(a.wa<h?r.width:0),e=h<c+1,c=n>c+q.width-1,g=k<a.ra+1,D=p>a.ra+q.height-1,E=!e&&!c,H=!g&&!D;e&&g&&d(a,-b,-b);e&&H&&d(a,-b,0);e&&D&&d(a,-b,b);E&&g&&d(a,0,-b);E&&D&&d(a,0,b);c&&g&&d(a,b,-b);c&&H&&d(a,b,0);c&&D&&d(a,b,b)}}),Q6(b,c,function(a){a.tf&&d(a,0,0)}));e.restore()};
var $ca=function(a,b,c,d,e,f,g,h,k,n){var p=(d-b)/h;h=(e-c)/h;var q=(f-d)/k;k=(g-e)/k;var r=(b-f)/n;n=(c-g)/n;a.beginPath();a.moveTo(Math.round(b+h),Math.round(c-p));a.lineTo(Math.round(d+h),Math.round(e-p));a.lineTo(Math.round(d+k),Math.round(e-q));a.lineTo(Math.round(f+k),Math.round(g-q));a.lineTo(Math.round(f+n),Math.round(g-r));a.lineTo(Math.round(b+n),Math.round(c-r));a.clip()};
var S6=function(a,b,c){y6.call(this,a,b,new B6);this.j=null;var d=this;_.M("imagery_viewer",function(b){d.j=b.j(a,_.R.W(),(0,_.t)(d.jp,d),(0,_.t)(d.kp,d),c);b=d.get("pano");var f=d.get("pov"),g=d.get("clickToGo"),h=d.get("scrollWheel"),k=d.get("panoProvider");_.I.addListener(d,"resize",function(){var b=_.wk(a);d.j.setSize((0,window.parseFloat)(b.width),(0,window.parseFloat)(b.height))});b&&d.j.setPano(b);f&&d.j.setPov(f);d.j.enableClickToGo(0!=g);d.j.enableScrollToZoom(0!=h);d.j.registerPanoProvider(k)});
this.O=!1};var T6=function(a){this.j=a;this.Sf=!1;this.O=0;_.I.bind(this,"panbyfraction",this,this.sm);_.I.bind(this,"panby",this,this.tm);_.I.bind(this,"pantobounds",this,this.um);_.I.bind(this,"dblclick",this,this.bp);_.I.bind(this,"mousewheel",this,this.rm);_.I.bind(this,"contextmenu",this,this.vm)};
var U6=function(a,b,c){var d=a.jg();if(b=_.Su(a.get("zoomRange"),d+b)-d){var d=a.get("size"),e=a.get("worldSize"),f=a.get("projection"),g=Math.pow(2,b),h=a.Yc(),h=f.Re(d,e,h,c),e=new _.O(e.width*g,e.height*g),h=new _.xc(h.heading,h.pitch,h.zoom+b),h=f.Qe(d,e,h,c);a.xd(h)}};var V6=function(){_.S.call(this);this.j=!1};
var W6=function(a,b){this.Jb=b;if("CH"==_.Ie(_.Ke(_.R))){var c=a;_.xC(c);c.style.fontSize="10px";c.style.height="17px";c.style.backgroundColor="#f5f5f5";c.style.border="1px solid #dcdcdc";c.style.lineHeight="19px"}else c=a,a=_.xJ(a),(_.sj()||_.FC())&&_.yJ(c);this.O=a;this.j=_.X("a",a);"CH"==_.Ie(_.Ke(_.R))?_.eM(this.j,!0):(this.j.style.textDecoration="none",this.j.style.color=_.sj()||_.FC()?"#fff":"#444");this.j.setAttribute("target","_new");_.ik("\u62a5\u544a\u95ee\u9898",this.j);this.j.setAttribute("title",
"\u5411 Google \u62a5\u544a\u8857\u666f\u56fe\u50cf\u95ee\u9898")};var X6=function(a){this.N=a||[]};var ada=function(a){a=a.N[0];return null!=a?a:""};var bda=function(a){a=a.N[1];return null!=a?a:""};var cda=function(a,b){a.N[2]=b};var dda=function(a,b){a.N[3]=b};
var Y6=function(a){_.LH.call(this,a,Z6);_.FF(a,Z6)||_.EF(a,Z6,{options:0},["div",,1,0,[" ",["div",,,9,[" ",["div",576,1,1,"Meeuwstraat 6"]," ",["div",576,1,2,"Ten Boer, The Netherlands"]," ",["div",,1,3,[" ",["a",,1,4,[" ",["div",576,1,5,"Simon Zwarts"]," "]]," "]]," "]]," ",["div",,,10]," ",["div",,,11,[" ",["a",,1,6,[" ",["div",,,12,[" ",["img",8,1,7]," "]]," "]]," "]]," ",["div",,,13]," ",["div",,,14,[" ",["a",,1,8,["\u5728Google\u5730\u56fe\u4e0a\u67e5\u770b"]]," "]]," "]],[["css",".gm-iv-address{background-color:#222222;opacity:0.8;font-family:Roboto,Arial;outline-color:#000;border-bottom-right-radius:2px;border-top-right-radius:2px;display:inline-block;padding:6px 10px;margin-top:10px}",
"css",".gm-iv-address-description{display:inline-block;max-width:310px}","css",".gm-iv-short-address-description{color:#fff;font-weight:bold;font-size:12px;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}","css",".gm-iv-long-address-description{color:#ccc;font-weight:normal;font-size:11px;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;min-width:70px;min-height:15px}","css",".gm-iv-vertical-separator{height:25px;display:inline-block;width:1px;margin-left:12px;background:-webkit-linear-gradient(top,#404040,#666,#404040);background:-moz-linear-gradient(top,#404040,#666,#404040);background:-ms-linear-gradient(top,#404040,#666,#404040);background:-linear-gradient(top,#404040,#666,#404040)}",
"css",".gm-iv-marker{display:inline-block;height:25px;width:13px;padding-left:4px}","css",".gm-iv-marker-icon{overflow:hidden;width:13px;height:21px;position:absolute;top:21px}","css",".gm-iv-marker-icon img{width:164px;height:112px;left:-17px;top:-49px;position:absolute}","css",".gm-iv-marker-icon img:hover{left:-1px}","css",".gm-iv-horizontal-separator{height:1px;background:-webkit-linear-gradient(left,#404040,#666,#404040);background:-moz-linear-gradient(left,#404040,#666,#404040);background:-ms-linear-gradient(left,#404040,#666,#404040);background:-linear-gradient(left,#404040,#666,#404040)}",
"css",".gm-iv-address-link a{color:#5c8dcc;text-decoration:none;font-size:11px}","css",".gm-iv-address-link a:hover{text-decoration:underline}","css",".gm-iv-profile-link{color:#fff;font-weight:bold;font-size:12px;padding-bottom:5px;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}","css",".gm-iv-profile-url a>.iv-profile-link:hover{text-decoration:underline}","css",".gm-iv-profile-url a{text-decoration:none}"]],eda())};var $6=function(a){return!_.bG(a.options,-6)};var a7=function(a){return a.vc};
var b7=function(a){return a.Kc};var c7=function(a){return a.Me};var d7=function(a){return a.lg};
var eda=function(){return[["$t","t-bDow0pNywiw","$a",[7,,,,,"gm-iv-address"]],["display",$6,"var",function(a){return a.Kc=_.aG(a.options,"",-1)},"$dc",[function(a,b){return a.og=b},a7,b7,!1],"$a",[7,,,,,"gm-iv-short-address-description"],"$c",[,,b7]],["display",$6,"var",function(a){return a.Me=_.aG(a.options,"",-2)},"$dc",[function(a,b){return a.zm=b},a7,c7,!1],"$a",[7,,,,,"gm-iv-long-address-description"],"$c",[,,c7]],["display",function(a){return _.bG(a.options,-6)},"$a",[7,,,,,"gm-iv-profile-url",
,1]],["$a",[8,1,,,function(a){return _.aG(a.options,"",-6)},"href",,,1],"$a",[0,,,,"_blank","target",,1]],["var",function(a){return a.lg=_.aG(a.options,"",-1)},"$dc",[function(a,b){return a.Am=b},a7,d7,!1],"$a",[7,,,,,"gm-iv-profile-link"],"$c",[,,d7]],["$a",[8,1,,,function(a){return _.aG(a.options,"",-4)},"href",,,1],"$a",[0,,,,"_blank","target",,1]],["$a",[8,2,,,function(a){return _.aG(a.options,"",-5)},"src",,,1],"$a",[0,,,,"false","draggable",,1]],["$a",[8,1,,,function(a){return _.aG(a.options,
"",-3)},"href",,,1],"$a",[0,,,,"_blank","target",,1]],["$a",[7,,,,,"gm-iv-address-description",,1]],["$a",[7,,,,,"gm-iv-vertical-separator",,1]],["$a",[7,,,,,"gm-iv-marker",,1]],["$a",[7,,,,,"gm-iv-marker-icon",,1]],["$a",[7,,,,,"gm-iv-horizontal-separator",,1]],["$a",[7,,,,,"gm-iv-address-link",,1]]]};
var e7=function(a,b,c,d){_.uC();a.setAttribute("dir",d?"rtl":"ltr");this.P=a;this.T=new _.de;this.S=d=new X6;d.N[4]=_.Ck("api-3/images/sv4");this.j=b=new Y6(b);this.U="?hl="+_.He(c).replace("_","-")+"&gl="+_.Ie(c);this.V=_.ri(c);this.O=_.wA(c);_.OH(b,a)};var f7=function(a){this.N=a||[]};
var g7=function(a){_.LH.call(this,a,h7);_.FF(a,h7)||_.EF(a,h7,{options:0},["div",,1,0,[" ",["div",,,2,[" ",["div",,,3,[" ",["div",,,4,[" ",["img",8,1,1]," "]]," "]]," "]]," "]],[["css",".gm-iv-container{width:27px;height:58px;margin-top:10px;border-right:1px solid #666;background-color:#222222;opacity:0.8;font-family:Roboto,Arial}","css",".gm-iv-close{width:27px;height:27px;margin-top:15px;outline-color:#000;display:inline-block}","css",".gm-iv-back{display:inline-block;height:15px;width:15px;padding:6px}",
"css",".gm-iv-back-icon{cursor:pointer;overflow:hidden;width:15px;height:15px;position:absolute}","css",".gm-iv-back-icon img{width:164px;height:112px;left:-3px;top:-71px;position:absolute}","css",".gm-iv-back-icon img:hover{left:-40px}","css",".gm-iv-back-icon img:active{left:-21px}"]],fda())};
var fda=function(){return[["$t","t-_EPk2VOG1I0","$a",[7,,,,,"gm-iv-container"]],["$a",[8,2,,,function(a){return _.aG(a.options,"",-1)},"src",,,1],"$a",[0,,,,"false","draggable",,1]],["$a",[7,,,,,"gm-iv-close",,1],"$a",[22,,,,"closeControl.click","jsaction",,1]],["$a",[7,,,,,"gm-iv-back",,1]],["$a",[7,,,,,"gm-iv-back-icon",,1]]]};
var i7=function(a,b,c,d){a.setAttribute("dir",d?"rtl":"ltr");this.j=a;d=new f7;d.N[0]=_.Ck("api-3/images/sv4");this.O=b=new g7(b);_.OH(b,a);_.gM(this.O,a,[d],_.la());var e=this;_.HI(c,"closeControl.click","click",function(){_.I.trigger(e,"closeclick")});_.CI(c.j,a)};
var j7=function(a,b){this.j=a;this.T=b;this.P=null;if(window.document.fullscreenEnabled||window.document.webkitFullscreenEnabled||window.document.mozFullScreenEnabled||window.document.msFullscreenEnabled){this.P=_.GB(_.Ck("api-3/images/sv4"),b,new _.N(0,-86),new _.O(164,112));b.style.width=_.V(25);b.style.height=_.V(25);b.style.marginRight=_.V(20);b.style.marginTop=_.V(10);b.style.overflow="hidden";_.I.addDomListener(b,"click",(0,_.t)(this.U,this));var c=(0,_.t)(this.S,this);_.I.addDomListener(window.document,
"fullscreenchange",c);_.I.addDomListener(window.document,"webkitfullscreenchange",c);_.I.addDomListener(window.document,"mozfullscreenchange",c);_.I.addDomListener(window.document,"MSFullscreenChange",c)}this.O=!1};var k7=function(a){return(a=a.exec(_.gc))?a[1]:""};var gda=function(a,b,c){var d=new _.ww(a);d.bindTo("disabled",c,"disableMomentum");_.G(["movestart","move","moveend"],function(a){_.I.forward(d,a,b)})};
var hda=function(a,b){_.G("click dblclick mousemove mouseout movestart move moveend".split(" "),function(c){_.I.forward(b,c,a)})};var l7=function(a){return"expwebgl"==a||"exphtml5"==a||"exphtml4"==a?!0:"exp"==a?_.Uc&&!_.Aj("9")||4==_.W.j||5==_.W.j||6==_.W.j?!1:_.oC():!1};
var ida=function(a,b,c){var d=a.Ha,e=new V6,f=new T6(d),g=new T6(d),h=new L5,k=a.j;h.bindTo("povFinal",k);e.bindTo("devZoom",b,"zoom");e.bindTo("devPov",b,"pov");h.bindTo("pov",e,"internalPov");g.bindTo("zoomRange",k);g.bindTo("zoom",k,"zoomFinal");g.bindTo("heading",k,"headingFinal");g.bindTo("pov",k,"povFinal");g.bindTo("layoutBounds",k);g.bindTo("disableDoubleClickZoom",b);f.bindTo("zoomRange",k);f.bindTo("zoom",k);f.bindTo("heading",k);f.bindTo("pov",e,"internalPov");_.I.forward(a,"panby",f);
_.I.forward(a,"panbyfraction",g);_.I.forward(b.__gm,"pantobounds",g);_.I.forward(a,"dblclick",g);_.I.tb(d,"contextmenu",g,!0);_.I.forward(a,"mousewheel",f);var n;n=b.get("mode")||"";var p=_.T[39];if(_.uJ()&&!p||"exp"==n&&l7(n)){n=!1;m7&&_.Aj("27")&&(n=!0);m7&&_.Hg&&(n=!1);n7&&_.Aj("22")&&(n=!0);_.Eg&&_.Aj("15")&&(n=!0);_.Uc&&_.Aj("11")&&(n=!0);!_.Fg||0<=_.cj(jda,"10.8.3")||(n=!1);var q=_.gc;_.Gg&&q&&(0<=q.indexOf("WindowsVista")||0<=q.indexOf("Windows NT 6.0"))&&(n=!1);_.Gg&&q&&(0<=q.indexOf("WindowsXP")||
0<=q.indexOf("Windows XP")||0<=q.indexOf("Windows NT 5.1"))&&(n=!1);0<=q.indexOf("CrOS armv")&&(n=!1);0<=q.indexOf("CrOS i686")&&(n=!1);n=n?"expwebgl":"exphtml5"}if((_.uJ()||p)&&"expwebgl"==n&&d)d={view:new S6(d,c,n),mode:"Siw"};else if((_.uJ()||p)&&"exphtml5"==n&&d)d={view:new S6(d,c,n),mode:"Sic"};else if(p&&"exphtml4"==n&&d)d={view:new S6(d,c,n),mode:"Si4"};else if("webgl"==n)d={view:new D6(d,c),mode:"Snw"};else{if(!(p="html5"==n)){if(p=4!=_.W.type&&5!=_.W.type&&_.W.U)if(p=_.oC())null!=o7?p=o7:
(p=window.document.createElement("canvas"),p=p.getContext&&p.getContext("2d"),p=o7=!(!p||!p.transform));p=p&&!n}d=p?{view:new N6(d,c),mode:"Snc"}:{view:new F6(d,c),mode:"Sn4"}}n=d;d=a.view=n.view;_.Y(b,n.mode);n=b.__gm;d.bindTo("imageDateControl",b);d.bindTo("clickToGo",b);d.bindTo("scrollWheel",b);d.bindTo("panoProvider",b);d.bindTo("position",b);d.bindTo("pov",f);d.bindTo("zoom",f);d.bindTo("visible",b);d.bindTo("links",b);d.bindTo("location",b);d.bindTo("copyright",k);d.bindTo("pano",b);d.bindTo("result",
n);d.bindTo("inMotion",h);b.bindTo("photographerPov",d);b.bindTo("status",d,"status",!0);null!=k.get("heading")&&n.set("heading",k.get("heading"));k.bindTo("heading",n);k.bindTo("size",d);k.bindTo("pov",d);k.bindTo("links",d);k.bindTo("pano",d);k.bindTo("location",d);k.bindTo("description",d);k.bindTo("floors",d);k.bindTo("floorId",d);k.bindTo("depthMap",d);k.bindTo("disabled",d);k.bindTo("headingOffset",d);k.bindTo("panoMap",d);k.bindTo("panoyawdeg",d);k.bindTo("position",d);k.bindTo("projection",
d);k.bindTo("tiltyawdeg",d);k.bindTo("worldSize",d);h=a.projection;n.bindTo("latLngBounds",d);h.bindTo("worldSize",d);h.bindTo("size",d);h.bindTo("projection",d);f.bindTo("projection",d);f.bindTo("worldSize",d);f.bindTo("size",d);g.bindTo("projection",d);g.bindTo("worldSize",d);g.bindTo("size",d);gda(a,d,b);_.I.forward(b,"resize",d);_.I.forward(a.O,"resize",d);_.I.tb(window,"resize",d);a=new i6(c);a.bindTo("pov",e,"internalPov");a.bindTo("pano",b);a.bindTo("scene",d)};
var kda=function(a,b){var c=b.getContainer(),d=new _.Kx(c,{},{Oi:!1,rj:_.ri(_.Ke(_.R))});a.Ha=d.P;a.O=d.j;d.O.style.backgroundColor=c.style.backgroundColor;_.qk(d.j,1);_.BC(d.j,!!b.getVisible());_.I.addListener(b,"visible_changed",function(){var a=!!b.getVisible();_.BC(d.j,a);a&&(_.I.trigger(b,"resize"),_.il("Sp","-p",b,!1))});b.__gm.set("panes",d.S)};
var lda=function(a,b){function c(){b.set("projection",d.get("pov")&&d.get("position")&&d.get("worldSize")&&d.get("size")&&d)}var d=a.projection=new d6;d.bindTo("position",b);d.bindTo("pov",b);var e=b.__gm;e.set("offset",new _.O(0,0));e.set("zoom",0);e.set("projectionTopLeft",new _.N(0,0));_.G(["position","pov","worldSize","size"],function(a){_.I.addListener(d,a.toLowerCase()+"_changed",c)})};
var mda=function(a,b,c){var d=a.Ha,e=new _.Sl(d,!0,void 0);hda(a,e);var f=new c.cl(d,!0);f.bindTo("zoom",a.j,"zoomFinal");_.I.forward(f,"panbyfraction",a);_.I.forward(f,"panby",a);if(nda(b)){c=new _.Hv(d);c.bindTo("enabled",b,"scrollwheel");_.I.forward(c,"mousewheel",a);var g=_.X("div",d,_.tg);g.className="gmnoprint";_.qk(g,2);_.nf(g,_.of(d));_.M("geometry",function(c){function d(){var c=b.get("linksControl"),e=b.get("disableDefaultUI");!_.B(c)&&!e||c?p.bindTo("links",a.j):(p.unbind("links"),p.set("links",
null))}var e;_.Uj()&&(e=new g6(g,c.computeHeading,c.computeOffset),e.bindTo("clickToGo",b),e.bindTo("linksControl",b),e.bindTo("disableDefaultUI",b),e.bindTo("pano",a.j),e.bindTo("size",a.j),e.bindTo("pov",a.j),e.bindTo("depthMap",a.j),e.bindTo("disabled",a.j),e.bindTo("headingOffset",a.j),e.bindTo("panoMap",a.j),e.bindTo("panoyawdeg",a.j),e.bindTo("position",a.j),e.bindTo("projection",a.j),e.bindTo("tiltyawdeg",a.j),e.bindTo("worldSize",a.j),_.I.forward(a.view,"move",e),_.I.forward(a,"mousemove",
e),_.I.forward(a,"mouseout",e),_.I.forward(a,"click",e),_.I.forward(f,"panbyfraction",e),_.I.forward(f,"panby",e),_.I.forward(f,"keydown",e));var p=new Y5(g);p.bindTo("pov",a.j);p.bindTo("pano",a.j);p.bindTo("size",a.j);p.bindTo("worldSize",a.j);e&&e.bindTo("linksHovering",p,"hovering");d();_.I.forward(f,"keydown",p);_.I.addListener(b,"linkscontrol_changed",d);_.I.addListener(b,"disabledefaultui_changed",d)})}_.I.addListenerOnce(a,"click",function(){_.il("Sp","-i",b,!1)})};
var p7=function(a,b){var c=a.get("addressControl"),d=a.get("disableDefaultUI");_.BC(b,!_.B(c)&&!d||c);_.I.trigger(b,"resize")};var q7=function(a,b,c){a=a.get("addressControlOptions");b.O(c);b.j(c,a&&a.position||1)};
var oda=function(a,b,c){var d=_.X("div");p7(b,d);q7(b,c,d);_.MB(d);_.I.addListener(b,"addresscontrol_changed",_.Ij(p7,b,d));_.I.addListener(b,"addresscontroloptions_changed",_.Ij(q7,b,c,d));_.I.addListener(b,"disabledefaultui_changed",_.Ij(p7,b,d));c=new e7(d,r7,_.Ke(_.R),_.Tx.j);c.bindTo("location",a.j);c.bindTo("pano",a.j);c.bindTo("pov",a.j);c.bindTo("options",b,"addressControlOptions")};var pda=function(a,b){var c=_.X("div");new j7(a,c);b.j(c,3)};
var qda=function(a,b,c){if(!a.S){var d=_.X("div");_.BC(d,!0);_.I.trigger(d,"resize");q7(b,c,d);_.MB(d);_.I.addListener(b,"addresscontroloptions_changed",_.Ij(q7,b,c,d));c=new _.FI(new _.rI);a=a.S=new i7(d,r7,c,_.Tx.j);a.bindTo("enableCloseButton",b);_.I.forward(a,"closeclick",b)}};
var rda=function(a,b,c){var d=_.X("div");_.qk(d,1);d.style.margin=_.V(10);p7(b,d);q7(b,c,d);_.MB(d);_.I.addListener(b,"addresscontrol_changed",_.Ij(p7,b,d));_.I.addListener(b,"addresscontroloptions_changed",_.Ij(q7,b,c,d));_.I.addListener(b,"disabledefaultui_changed",_.Ij(p7,b,d));c=new K5(d);c.bindTo("description",a.j);c.bindTo("options",b,"addressControlOptions")};
var sda=function(a,b,c){if(!a.P){var d=_.X("div");_.MB(d);d.className="gmnoprint";_.qk(d,1);d.style.margin=_.V(3);c.j(d,3);a=a.P=new M5(d);a.bindTo("closeEnabled",b,"enableCloseButton");_.I.forward(a,"closeclick",b)}};var tda=function(a,b){var c=_.X("div");(new J5(c)).bindTo("disabled",a.view);b.j(c,13)};
var uda=function(a,b,c,d){var e=_.X("div");d=new W6(e,d);d.bindTo("pano",a.view);d.bindTo("pov",b);d.bindTo("takeDownUrl",a.view);_.T[17]&&(d.bindTo("visible",b,"reportErrorControl"),b.bindTo("rmiLinkData",d));c.j(e,12,!1,-1003);b.set("rmiWidth",e.offsetWidth)};var vda=function(a){_.SC(function(b){b.fr(a.get("pov"));_.I.addListener(a,"position_changed",function(){b.dr(a.get("position"))});_.I.addListener(a,"pov_changed",function(){b.er(a.get("pov"))})})};
var wda=function(){_.M("util",function(a){window.setTimeout((0,_.t)(a.Mf.ek,a.Mf),5E3)})};var nda=function(a){a=a.get("mode")||"";return!(l7(a)||_.uJ())};
var s7=function(a,b,c){this.ta=b;this.Cd=c;var d=_.X("div",a);this.S=d;_.AC(d);a=_.mJ();this.O=a.sk;this.V=a.Rj;a=_.rJ(d,this.V,0);_.hk(a,new _.N(this.O.Ma.width,this.O.Ma.height));b=new _.N((this.V.Ma.width-94)/2,5);c=new _.O(94,75);var e=_.X("div",a,b,c);this.oa=e;e.style.backgroundColor="#d3d3d3";_.qk(e,1);_.AC(e);e=_.X("div",a);e.style.width=_.V(95);e.style.bottom="38px";_.qk(e,1);e.style.left=_.V(b.x);e.style.fontFamily="Roboto,Arial,sans-serif";e.style.fontSize=_.V(9);e.style.color="gray";e.style.backgroundColor=
"white";this.U=_.ik("",e);_.lk(e);this.P=3;this.qa=d=_.rJ(d,this.O,this.P);_.hk(d,t7[this.P]);d={Bc:(0,_.t)(this.Aa,this)};this.j=_.GB(null,a,b,c,d);this.na=!0;this.T=new _.N(0,0)};
var u7=function(a,b){for(var c="",d=0,d=0;d<vca(a.getAttribution());++d){var e;e=a.getAttribution();var f=d;e=new w3(_.Q(e.N,0)[f]);c=c+(" "+e4(c4(e)))}(c=c.substr(1))||(c+="\u00a9 "+e4(c4(d4(a.getAttribution()))));e=new _.L(W3(Z3(y3(a,0).getLocation())),V3(Z3(y3(a,0).getLocation())));for(var g=f=e4(b4(B3(a),0)),d=1;d<_.Fc(B3(a).N,2);++d)f+=", "+e4(b4(B3(a),d));f||(g=f=e4(c4(d4(a.getAttribution()))));var d=(d=a.N[1])?new _.sM(d):_.nP,h=3==$3(d)?"F:"+d.getId():d.getId(),f={latLng:e,shortDescription:g,
description:f,pano:h};null!=d4(a.getAttribution()).N[1]&&(f.profileUrl=d4(a.getAttribution()).getUrl());for(var k=g=0,n=[],p,q=[],r=[],d=0;d<_.Fc(a.N,5);++d){var v=y3(a,d);null!=v.getLocation().N[2]&&(g=Y3(v.getLocation()).getHeading(),k=Y3(v.getLocation()).getTilt(),v.getLocation());null!=v.getLocation().N[3]&&(p=U3(X3(v.getLocation())));var x;for(x=0;x<_.Fc(v.N,6);++x){var w=x,w=(new M3(_.Q(v.N,6)[w])).N[0],w=J3(v).getTarget(null!=w?w:0),z=I3(w).getId();3==$3(I3(w))&&(z="F:"+h);var F=w.N[3],F=e4(b4(F?
new _.mM(F):_.uO,0)),w=new _.L(W3(Z3(w.getLocation())),V3(Z3(w.getLocation())));n.push({description:F,heading:b(e,w),pano:z})}for(x=0;x<_.Fc(v.N,7);++x){var w=x,w=(new L3(_.Q(v.N,7)[w])).N[0],w=J3(v).getTarget(null!=w?w:0),z=X3(w.getLocation()),F=z.N[1],D=z.N[2],E=z.N[3];q.push({ti:e4(E?new _.jM(E):_.lO),description:e4(D?new _.jM(D):_.kO),ce:U3(z),fh:null!=F?F:0,Kj:I3(w).getId()})}for(x=0;x<_.Fc(v.N,12);++x)for(w=x,w=new O3(_.Q(v.N,12)[w]),z=0;z<_.Fc(w.N,1);++z)r.push(sca(w,z))}xda(n,r);var H;null!=
a4(A3(a)).N[0]&&(H=a4(A3(a)).N[0],H=null!=H?H:0,null!=a4(A3(a)).N[1]&&(d=a4(A3(a)).N[1],H+=" - "+(null!=d?d:0)));d=z3(a).N[0];e=z3(a).N[1];return{copyright:c,imageDate:H,location:f,links:n,tiles:{centerHeading:g,originHeading:g,originPitch:k-90,tileSize:new _.O(S3(P3(Q3(C3(a)))),T3(P3(Q3(C3(a))))),worldSize:new _.O(S3(R3(C3(a))),T3(R3(C3(a))))},disabled:1!=(null!=e?e:1),ce:p,bj:q,takeDownUrl:null!=d?d:""}};
var xda=function(a,b){if(b.length&&!(5<b.length)&&b.length==a.length){for(var c=Jca(b),d=window.Infinity,e=[],f=0;f<c.length;++f){var g=c[f],h=Ica(g,function(b,c,d){c=_.Ia(c-a[d].heading,-180,180);return b+c*c});h<d&&(d=h,e=g)}for(c=0;c<e.length;++c)a[c].heading=e[c]}};var yda=function(a){var b=[];_.G(a,function(a){(a.headingDeg||a.yawDeg)&&b.push({heading:_.Gj(a.headingDeg||a.yawDeg),description:a.description,pano:a.panoId})});return b};
var v7=function(){throw Error("unimplemented abstract method");};var w7=function(a,b,c,d,e,f,g){e=e||new _.oI(_.yA());f={output:"json",oe:"utf-8",it:zda[f||"default"]};_.Uj()&&(f.dmz=1,f.pmz=1);g&&(f.rank=g);f[a]=b;_.C(c)&&(f.radius=c);a=f4(e,f);_.Lk(window.document,_.jh,e.j.getUrl(0),_.Rf,a,Ada(d),Bda(d))};var Bda=function(a){return function(){a(null,_.ja)}};
var Ada=function(a){return function(b){if(b){var c=b.Data,d=new Hca,e,f,g=b.model;if(g){var h=g.uncompressed_depth_map,g=g.uncompressed_pano_map;if(h){var k=new H5;I5(k,h);e=new Gca(k,d)}g&&(k=new H5,I5(k,g),f=new Fca(k))}var n;if(d=b.levels&&b.levels.level)for(n=[],h=0,g=d.length;h<g;++h)n.push({ti:d[h].abbreviation,Kj:d[h].pano_id,fh:(0,window.parseFloat)(d[h].ordinal),description:d[h].text,ce:d[h].level_id});d=!(!c||!c.disabled);if(h=b.Location)var h=b.Location,k=h.region,p=h.description,q=h.streetRange+
(" "+h.description),r=h.region+h.description,v=h.region+(h.streetRange+h.description),g=h.streetRange?q:p,k=h.streetRange?h.region?v:q:h.region?h.description?r:k:p,h={latLng:new _.L(Number(h.lat),Number(h.lng)),shortDescription:g,description:k,pano:h.panoId};(_.T[43]||_.sj()||_.FC())&&b.Location&&b.Location.text_url&&(h.profileUrl=b.Location.text_url);g=b.Result;k=c&&c.copyright;p=c&&c.image_date;q=yda(b.Links);r=b.Data;v=b.Projection;b={result:g,location:h,copyright:k,imageDate:p,links:q,tiles:{worldSize:r&&
new _.O(_.Gj(r.image_width),_.Gj(r.image_height)),tileSize:r&&new _.O(_.Gj(r.tile_width),_.Gj(r.tile_height)),centerHeading:v&&Number(v.pano_heading_deg||v.pano_yaw_deg),originHeading:v&&Number(v.pano_heading_deg||v.pano_yaw_deg),originPitch:Number(v&&v.tilt_pitch_deg||"0"),originPitchYaw:Number(v&&v.tilt_yaw_deg||"0")},zn:e,disabled:d,ce:b.Location&&b.Location.level_id,bj:n,Np:f,rh:c&&c.scene};a(b,_.ga)}else a(null,_.ka)}};
var Cda=function(a,b,c){var d=new z5,e=yca();x7(d);var f=zca(Dca(d));"F:"==a.substring(0,2)?(f.N[1]=a.substring(2),f.N[0]=3,_.ri(_.Ke(_.R))||(e=e.replace("http:","https:"))):(f.N[1]=a,f.N[0]=2);_.Lk(window.document,_.jh,e,null,"pb="+Cca(d),_.Ij(Dda,b,c),function(){b(null,_.ja)})};var Dda=function(a,b,c){var d=new y5(c);c=_.ja;null!=d.N[0]&&0==E3(d.getStatus())&&(c=_.ga);d=new _.aN(_.Q(d.N,1)[0]);a(u7(d,b),c)};
var Eda=function(a,b,c){var d=new f5;x7(d);var e=xca(),f=G3(F3(x5(d)));f.N[0]=2;f.N[1]=!0;f.N[2]=2;_.ri(_.Ke(_.R))||(f=G3(F3(x5(d))),f.N[0]=3,f.N[1]=!0,f.N[2]=2,e=e.replace("http:","https:"));f=a.location;uca(H3(w5(d)),f.lat());tca(H3(w5(d)),f.lng());f=_.qa(a.radius)?a.radius:50;w5(d).setRadius(f);qca(oca(x5(d)),"best"==a.preference?1:2);"outdoor"==a.source&&rca(pca(x5(d)));_.Lk(window.document,_.jh,e,null,"pb="+Bca(d),_.Ij(Fda,b,c),function(){b(null,_.ja)})};
var Fda=function(a,b,c){c=new L4(c);var d=_.ja;null!=c.N[0]&&0==E3(c.getStatus())&&(d=_.ga);a(u7(c.getMetadata(),b),d)};var x7=function(a){var b=a.cj();b.N[0]="apiv3";_.qa(void 0)&&(b.N[2]="undefined");b.N[4]=_.Ie(_.Ke(_.R));b.N[10]=b.N[10]||[];b=new _.IM(b.N[10]);b.N[0]=b.N[0]||[];(new _.HM(b.N[0])).N[0]=!!_.T[56];a=a.Cj();D3(a,1);D3(a,2);D3(a,3);D3(a,4);D3(a,8);D3(a,6);b=[];_.Q(a.N,4).push(b);(new K3(b)).N[0]=2;b=[];_.Q(a.N,5).push(b);(new N3(b)).N[0]=2};var y7=function(){};t3.prototype.W=_.l("N");
u3.prototype.W=_.l("N");v3.prototype.W=_.l("N");v3.prototype.getLocation=function(){var a=this.N[1];return a?new _.uM(a):_.qO};v3.prototype.getTime=function(a){return new t3(_.Q(this.N,8)[a])};w3.prototype.W=_.l("N");w3.prototype.getUrl=function(){var a=this.N[1];return null!=a?a:""};w3.prototype.setUrl=function(a){this.N[1]=a};K3.prototype.W=_.l("N");L3.prototype.W=_.l("N");M3.prototype.W=_.l("N");N3.prototype.W=_.l("N");O3.prototype.W=_.l("N");
var h4,p5,j4,D4,o5,l5,G4,s5,D5,l4,v4,C4,B4,E4,I4,q5,u5,n5,t5,k5,F4,m5,r5,y4,w4,x4,u4,i5,n4,p4,r4,C5,H4,v5,t4,B5,A4,j5,h5,g5,A5;J4.prototype.W=_.l("N");var o7;L4.prototype.W=_.l("N");L4.prototype.getStatus=function(){var a=this.N[0];return a?new _.XM(a):_.zP};L4.prototype.getMetadata=function(){var a=this.N[1];return a?new _.aN(a):_.AP};L4.prototype.getTile=function(){var a=this.N[3];return a?new _.dN(a):_.BP};_.m=f5.prototype;_.m.W=_.l("N");
_.m.getContext=function(){var a=this.N[0];return a?new _.WM(a):_.tP};_.m.cj=function(){this.N[0]=this.N[0]||[];return new _.WM(this.N[0])};_.m.getLocation=function(){var a=this.N[1];return a?new _.EM(a):_.uP};_.m.Cj=function(){this.N[3]=this.N[3]||[];return new _.ZM(this.N[3])};y5.prototype.W=_.l("N");y5.prototype.getStatus=function(){var a=this.N[0];return a?new _.XM(a):_.iP};_.m=z5.prototype;_.m.W=_.l("N");_.m.getContext=function(){var a=this.N[0];return a?new _.WM(a):_.fP};
_.m.cj=function(){this.N[0]=this.N[0]||[];return new _.WM(this.N[0])};_.m.Cj=function(){this.N[3]=this.N[3]||[];return new _.ZM(this.N[3])};_.m.getQuery=function(a){return new J4(_.Q(this.N,2)[a])};_.y(J5,_.J);J5.prototype.disabled_changed=function(){_.BC(this.j,!!this.get("disabled"))};_.y(K5,_.J);K5.prototype.description_changed=function(){var a=this.get("description")||"";_.CC(this.O,a);_.BC(this.j,!!a);_.I.trigger(this.j,"resize")};_.y(L5,_.J);_.m=L5.prototype;_.m.pov_changed=function(){this.P||this.zq(this.gg())};_.m.povFinal_changed=function(){var a=this.gg(),b=this.jj();b&&(a&&b&&a.heading==b.heading&&a.pitch==b.pitch&&a.zoom==b.zoom?(this.O.reset(),this.j&&(window.clearTimeout(this.j),this.j=0,this.set("inMotion",!1))):(this.O.extend(10),this.S=this.gg(),this.j||(this.set("inMotion",!0),this.rk())))};
_.m.rk=function(){var a=this.O.next(),b=this.S,c=this.jj(),a=new _.xc(c.heading+(b.heading-c.heading)*(1-a),b.pitch+(c.pitch-b.pitch)*a,b.zoom+(c.zoom-b.zoom)*a);this.P=!0;this.set("pov",a);this.P=!1;_.Uu(this.O)?this.j=window.setTimeout((0,_.t)(this.rk,this),0):(this.j=0,this.set("inMotion",!1))};_.m.gg=_.K("pov");_.m.zq=_.Gb("povFinal");_.m.jj=_.K("povFinal");_.y(M5,_.J);M5.prototype.changed=function(){var a=this.get("closeEnabled");_.BC(this.P,a);var b=this.O.Ma;_.nf(this.T,new _.O(a?b.width:0,b.height))};var P5=[0,-120,60,-60,40,-30,-40,-30,-60,-60,0,-120],Kca=new _.O(120,90),Q5=[0,-100,40,-60,30,-50,0,-82,-30,-50,-40,-60];_.y(N5,_.J);N5.prototype.release=function(){_.G(this.Ba,_.I.removeListener);this.Ba.length=0;_.nj(this.P)};
N5.prototype.Ia=function(a,b,c){a=this.S.heading-a.heading;var d=this.O.context;d.save();d.translate(b.x,b.y);d.scale(1,c);d.rotate(_.A(a));var e=this.j||"#FFFFFF",f=1,g;_.C(f)||(f=1);if(e&&"#"==e.charAt(0)){var h=new _.KI;h.P=(0,window.parseInt)(e.slice(1,3),16);h.O=(0,window.parseInt)(e.slice(3,5),16);h.j=(0,window.parseInt)(e.slice(5,7),16);h.alpha=f;0<=h.P&&256>h.P&&0<=h.O&&256>h.O&&0<=h.j&&256>h.j&&0<=h.alpha&&1>=h.alpha&&(g="rgba("+[h.P,h.O,h.j,h.alpha].join(", ")+")")}d.fillStyle=g||e;g=this.O.context;
g.beginPath();g.moveTo(Q5[0],Q5[1]);for(e=2;e<Q5.length;e+=2)g.lineTo(Q5[e],Q5[e+1]);g.closePath();g.fill();d.restore();d=this.P;(g=_.sk.j)&&(d.style[g]="translate("+Math.round(b.x)+"px,"+Math.round(b.y)+"px) scale(1, "+c+") rotate("+Math.round(a)+"deg) translate(-60px, -120px)")};_.y(O5,_.J);O5.prototype.release=function(){_.G(this.Ba,_.I.removeListener);this.Ba.length=0;_.nj(this.S);_.nj(this.O);_.nj(this.P);this.j&&_.nj(this.j)};
O5.prototype.Ia=function(a,b,c){a=this.T-a.heading;var d=_.A(a),e=Math.cos(d),d=Math.sin(d),f=.8<Math.abs(e),g=b.x;b=b.y;var h=a+(f?0:(0<d?90:-90)-_.Ka(Math.atan2(d,e*c)));U5(this.S,a,g,b,c);U5(this.O,a,g,b-3,c);U5(this.P,a,g,b-3,c);this.j&&(U5(this.j,a,g,Math.round(b+140*e*(1-c)),1,Math.round(-h),0,-140),this.j.setAttribute("text-anchor",f?"middle":0<d?"start":"end"))};_.y(V5,_.J);V5.prototype.release=function(){_.G(this.Ba,_.I.removeListener);this.Ba.length=0;_.nj(this.U);_.nj(this.S);_.nj(this.V);this.O&&_.nj(this.O)};V5.prototype.Ia=function(a,b,c){a=this.T-a.heading;X5(this.na,a,0,c);X5(this.oa,a,.5,c);X5(this.qa,a,0,c);var d=_.A(a);b=Math.cos(d);var d=Math.sin(d),e=.8<Math.abs(b),f=a+(e?0:(0<d?90:-90)-_.Ka(Math.atan2(d,b*c)));this.P&&X5(this.P,a,140*b*(1-c)+(e?0:-7),1,-f,0,-140);this.j&&(this.j.style["v-text-align"]=e?"center":0<d?"left":"right")};_.y(Y5,_.S);_.m=Y5.prototype;_.m.release=function(){_.I.removeListener(this.T);this.T=null;_.I.removeListener(this.V);this.V=null;Z5(this)};_.m.size_changed=function(){var a=this.get("size");a&&(_.pC()?this.j=_.tJ(this.O,a):_.JB()?this.j=_.sJ(this.O,a):_.CD()&&(this.j||(this.j=_.AD("group",this.O)),_.nf(this.j,a),_.hk(this.j,_.tg),this.j.coordsize=Math.round(a.width)+","+Math.round(a.height)),$5(this));this.Ca()};_.m.links_changed=function(){this.S=!0;this.Ca()};
_.m.pov_changed=function(){$5(this);this.Ca()};_.m.center_changed=function(){var a=this.get("center");a&&this.j&&(this.j.coordorigin=Math.round(-a.x)+","+Math.round(-a.y));this.Ca()};_.m.Ia=function(){this.S&&(Z5(this),Nca(this),this.S=!1);Mca(this);var a=this.get("worldSize"),b=this.get("size"),c=this.get("pov"),d=this.get("center"),e=this.get("yScale");c&&_.C(c.heading)&&d&&_.C(e)&&b&&a&&_.G(this.P,function(a){a.Ia(c,d,e)})};
_.m.pp=function(a){var b=a.target;if(b=b&&b.getAttribute("pano"))this.set("pano",b),_.Za(a)};_.m.hm=function(a){var b=a.keyCode;if(38==b||40==b){var c=this.get("pov").heading;40==b&&(c+=180);var d,e=200;_.G(this.get("links"),function(a){var b=Math.abs(_.Ia(_.Gj(a.heading)-c,-180,180));b<e&&(e=b,d=a.pano)});d&&(this.set("pano",d),_.Za(a))}};_.y(c6,_.J);c6.prototype.map_changed=function(){var a=this.j;if(this.pa){for(var b=this.pa.overlayMapTypes,c=0,d=b.getLength();c<d;++c)if(a==b.getAt(c)){b.removeAt(c);break}a.unbind("mapHeading");a.unbind("tilt")}if(b=this.pa=this.get("map"))a.bindTo("mapHeading",b,"heading"),a.bindTo("tilt",b),a.bindTo("client",b,"svClient"),b=b.overlayMapTypes,b.push(a)};_.y(d6,_.J);d6.prototype.fromLatLngToPoint=function(a,b){var c=this.get("worldSize"),d=this.get("position"),e=this.get("pov"),f=this.j,g=this.get("projection"),h=this.get("size");if(!(c&&d&&e&&h&&g))return null;var k=b||new _.N(0,0),n=_.Ka(Math.atan2(_.Ia(a.lng()-d.lng(),-180,180)*Math.cos(_.A(d.lat())),a.lat()-d.lat())),d=_.Ka(Math.atan2(-3,.1+6378137*Eca(d,a)));f.x=n/360*c.width;f.y=(90-d)/180*c.height;c=g.Lj(f,h,c,e,0);if(!c)return null;k.x=c.x;k.y=c.y;return k};
d6.prototype.fromPointToLatLng=function(a,b){var c=this.get("worldSize"),d=this.get("position"),e=this.get("pov"),f=this.get("size"),g=this.get("projection");if(!(c&&d&&e&&f&&g))return null;f=g.Lf(a,f,c,e,0);e=f.x/c.width*360;c=Math.tan(_.A(90-f.y/c.height*180));-.01<c&&(c=-.01);var h=(-3/c-.1)/6378137,f=_.A(d.lat()),d=_.A(d.lng()),c=Math.cos(f),f=Math.sin(f),g=Math.cos(h),h=Math.sin(h),e=_.A(e),k=f*g+c*h*Math.cos(e);return new _.L(_.Ka(Math.asin(k)),_.Ka(d+Math.atan2(Math.sin(e)*h*c,g-f*k)),b)};_.y(e6,_.J);_.m=e6.prototype;_.m.visible_changed=function(){var a=!!this.get("visible");this.j.setAttribute("visibility",a?"visible":"hidden")};_.m.opacity_changed=function(){var a=this.get("opacity");this.j.setAttribute("fill-opacity",a)};_.m.shape_changed=function(){var a=0==this.get("shape")?this.O:this.P;this.j!=a&&(this.j.setAttribute("visibility","hidden"),this.j=a,this.visible_changed(),this.opacity_changed())};
_.m.wafflePoints_changed=function(){var a=this.get("wafflePoints");a&&4==a.length&&this.P.setAttribute("d","M"+a[0].x+" "+a[0].y+" L"+a[1].x+" "+a[1].y+" L"+a[2].x+" "+a[2].y+" L"+a[3].x+" "+a[3].y+" Z")};_.m.pancakePoints_changed=function(){var a=this.O,b=this.get("pancakePoints");b&&2==b.length&&(a.setAttribute("cx",(b[0].x+b[1].x)/2),a.setAttribute("cy",(b[0].y+b[1].y)/2),a.setAttribute("rx",Math.abs((b[0].x-b[1].x)/2)),a.setAttribute("ry",Math.abs((b[0].y-b[1].y)/2)))};_.y(f6,_.J);_.m=f6.prototype;_.m.visible_changed=function(){this.j.on=!!this.get("visible")};_.m.opacity_changed=function(){this.j.opacity=this.get("opacity")};_.m.shape_changed=function(){var a=0==this.get("shape")?this.O:this.T;this.j!=a&&(this.j.on=!1,this.j=a,this.visible_changed(),this.opacity_changed())};_.m.wafflePoints_changed=function(){var a=this.get("wafflePoints");a&&4==a.length&&(this.S.points.value=a[0].x+" "+a[0].y+" "+a[1].x+" "+a[1].y+" "+a[2].x+" "+a[2].y+" "+a[3].x+" "+a[3].y)};
_.m.pancakePoints_changed=function(){var a=this.get("pancakePoints");a&&2==a.length&&_.kk(this.P,{left:_.V(a[0].x),top:_.V(a[0].y),height:_.V(a[1].y-a[0].y),width:_.V(a[1].x-a[0].x)})};var Qca=2/(1+Math.sqrt(5));_.y(g6,_.J);_.m=g6.prototype;_.m.gm=function(){var a=this.get("pov");a&&this.T&&(a.heading!=this.T.heading||a.pitch!=this.T.pitch)&&h6(this,this.ta)};_.m.fm=function(a){a=_.gl(a,this.na);h6(this,a);this.ta=a};
_.m.rp=function(a){if(this.P)1==this.j.get("shape")&&(this.S=this.Ea(this.get("position"),this.oa,this.qa)),this.set("pano",this.P);else{var b=this.get("pov"),c=this.get("worldSize"),d=this.get("projection"),e=this.get("size");a=_.gl(a,this.na);d=d.Lf(a,e,c,b,0);e=d.x/c.width*360;e=_.Ia(e,b.heading-180,b.heading+180);this.V.set("povFinal",new _.xc(e,90-d.y/c.height*180,b.zoom))}};_.m.linksHovering_changed=function(){this.get("linksHovering")&&this.j.set("visible",!1)};
_.m.linksControl_changed=g6.prototype.disabled_changed=g6.prototype.disableDefaultUI_changed=g6.prototype.clickToGo_changed=function(){var a=this.get("disableDefaultUI"),b=this.get("clickToGo");(_.B(b)||a)&&!b||this.get("disabled")&&0!=this.get("linksControl")?(_.G(this.U,_.I.removeListener),this.U=null,this.j.set("visible",!1)):this.U||(this.U=[_.I.bind(this,"move",this,this.gm),_.I.bind(this,"mousemove",this,this.fm),_.I.bind(this,"click",this,this.rp),_.I.bind(this,"mouseout",this,this.ud),_.I.bind(this,
"keydown",this,this.ud),_.I.bind(this,"panbyfraction",this,this.ud),_.I.bind(this,"panby",this,this.ud)])};_.m.position_changed=function(){if(this.S){var a=this.Aa(this.get("position"),this.S),b=this.get("pov"),a=_.Ia(a,b.heading-180,b.heading+180);this.V.set("povFinal",new _.xc(a,b.pitch,b.zoom));this.j.set("visible",!1);this.S=null}};_.m.depthMap_changed=function(){this.ud()};_.m.ud=function(){this.j.set("visible",!1)};_.y(i6,_.S);i6.prototype.pano_changed=i6.prototype.pov_changed=function(){this.Ca()};
i6.prototype.Ia=function(){var a=this.get("pov"),b=this.get("pano"),c=this.get("scene");if(a&&b){var d=this.V!=b,e=1<=Math.abs(a.zoom-this.S),f=_.A(a.pitch),g=_.A(a.heading),a=a.zoom,h=Math.acos(Math.sin(this.j)*Math.sin(f)+Math.cos(this.j)*Math.cos(f)*Math.cos(this.O-g))>Math.atan(Math.pow(2,1-a))/2;if(e||h||d)"c"!=c&&(this.N.push({rh:"1"==c?68:67,pan:h,zoom:e,Nd:d}),this.P&&window.clearTimeout(this.P),this.P=_.IA(this,this.T,1E3)),this.O=g,this.j=f,this.S=a,this.V=b}};
i6.prototype.T=function(){var a="",b="";_.G(this.N,function(c){c=c.rh+":"+(c.Nd?"2":c.zoom?"1":"0")+";1,";c!=b&&(a+=c);b=c});this.N=[];var c={output:"cbrep",ed:a,s:Math.floor(1E5*Math.random())},d=this.Jb.j.getUrl(0)+f4(this.Jb,c);_.M("stats",function(a){a.Vc.th(d)})};j6.prototype.set=function(a,b,c){var d=Math.cos(b);b=Math.sin(b);var e=Math.cos(a);this.O=d*Math.sin(a);this.P=b;this.S=d*e;this.j=c};k6.prototype.getZoom=_.l("P");k6.prototype.clear=function(a){this.Gc&&a.deleteTexture(this.Gc);this.Gc=null};m6.prototype.getZoom=_.l("S");m6.prototype.getTile=function(a,b){return b<this.j?this.O[a*this.j+b]:null};m6.prototype.clear=function(a){for(var b=this.O,c=0,d=this.P*this.j;c<d;++c)b[c].clear(a)};_.m=n6.prototype;_.m.clear=function(){for(var a=0;a<=this.j;++a)this.O[a].clear(this.Aa);window.clearInterval(this.Ea)};_.m.Qq=function(a,b){a.getZoom()>this.j||a!=this.O[a.getZoom()].getTile(a.Kf,a.Ue)||(b?(l6(a,this.Aa),this.na&&this.na()):this.qa.push(a))};_.m.tk=function(a){a.Eh=!0};_.m.xm=function(){this.qa.length&&(l6(this.qa.shift(),this.Aa),this.na&&this.na())};
_.m.Io=function(a,b,c){var d=new j6;d.set(2*Math.PI*(b+.5)*c/(this.T*this.oa),Math.PI*(.5-(a+.5)*c/(this.U*this.ta)),2*Math.PI/Math.SQRT2*c/(this.T*this.oa));return d};q6.prototype.scale=function(a){for(var b=0;12>b;b++)this.m[b]*=a};q6.prototype.j=function(a){var b=new q6;r6(b);var c=Math.cos(a);a=Math.sin(a);b.m[0]=1;b.m[5]=c;b.m[6]=a;b.m[9]=-a;b.m[10]=c;b.m[15]=1;s6(this,b)};q6.prototype.O=function(a){var b=new q6;r6(b);var c=Math.cos(a);a=Math.sin(a);b.m[0]=c;b.m[2]=-a;b.m[5]=1;b.m[8]=a;b.m[10]=c;b.m[15]=1;s6(this,b)};q6.prototype.translate=function(a,b,c){this.m[3]+=a;this.m[7]+=b;this.m[11]+=c};t6.prototype.Zb=function(){if(this.O.S){this.j.finish();var a=this.U/this.T;this.Aa.set(this.qa+_.A(this.O.V.j),this.ta,.5*_.A(this.V)*Math.sqrt(1+a*a));var a=this.O,b=this.Aa,c=Math.min(this.O?Math.max(0,Math.min(this.O.j-Math.floor(_.fj(this.O.ta*this.O.U/Math.PI/(this.T/_.A(this.V)/this.O.V.Pf))-.5),this.O.j)):0,a.j);a.P=[];for(var d=[a.S],e=[a.S],f=a.P;d.length;){var g=d.shift(),h=e.shift();if(g.getZoom()>=c)g.Eh||o6(a,g),(h=g.Gc?g:h)&&f.push({Qp:g,Rq:h});else for(var h=g.Gc?g:h,k=0;4>k;++k){var n=
g.Of[k],p;if(p=n)p=n.rn,p=Math.acos(b.O*p.O+b.P*p.P+b.S*p.S)<b.j+p.j;p&&(d.push(n),e.push(h))}}this.S.m=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];this.S.scale(10);this.S.O(this.qa+_.A(this.O.V.j));this.S.j(-this.ta);s6(this.S,this.na);this.j.uniformMatrix4fv(this.j.getUniformLocation(this.P,"u_modelViewProjMatrix"),!1,new window.Float32Array(Sca(this.S)));a=this.O.P.length;b=null;for(c=0;c<a;++c)e=this.O.P[c],d=e.Qp,e=e.Rq,e.Gc&&(e!=b&&(this.j.bindTexture(this.j.TEXTURE_2D,e.Gc),this.j.uniformMatrix4fv(this.j.getUniformLocation(this.P,
"u_texTransMatrix"),!1,e.O),b=e),e=this.oa,e.j.drawElements(e.j.TRIANGLES,d.ih*e.Ea,e.j.UNSIGNED_SHORT,2*e.Ea*d.Gf))}};_.y(x6,_.J);x6.prototype.getPanoramaByLocation=function(a,b){var c=this,d=_.jB(c);this.j.getPanoramaByLocation(a,b,_.Va(function(a,b){_.iB(c,d)&&(c.set("result",a),c.set("status",b))}))};x6.prototype.getPanoramaById=function(a){var b=this,c=_.jB(b);this.j.getPanoramaById(a,_.Va(function(a,e){_.iB(b,c)&&(b.set("result",a),b.set("status",e))}))};var Uca="1 \u6708;2 \u6708;3 \u6708;4 \u6708;5 \u6708;6 \u6708;7 \u6708;8 \u6708;9 \u6708;10 \u6708;11 \u6708;12 \u6708".split(";");_.y(y6,_.S);_.m=y6.prototype;_.m.km=function(a){var b=this.Hd();b&&(this.Aa=this.pi().Re(this.vd(),b,this.getPov(),a.Ja),this.qa=!0)};_.m.lm=function(a){var b=this.Hd();b&&this.Aa&&this.set("pov",this.pi().Qe(this.vd(),b,this.Aa,a.Ja))};_.m.jm=function(){this.qa=!1;this.Ca()};_.m.oi=function(){var a=_.of(this.S);a.j(this.vd())||this.set("size",a)};
_.m.position_changed=function(){var a=this.getPosition();if(a){var b=this.getLocation();b&&b.latLng==a||this.na.getPanoramaByLocation(a,50);this.set("latLngBounds",_.mf(a,275/6378137))}};_.m.pano_changed=function(){var a=this.getPano(),b;if(a){var c=this.getLocation();if(!c||c.pano!=a){var d=this;_.Wa(function(){var c=d.get("panoProvider");c&&(b=c(a))&&(b.code=200,b.scene="c",d.set("result",b));b||d.na.getPanoramaById(a)})}}};
_.m.result_changed=function(){var a=this.get("result");a&&(this.set("tiles",a.tiles),this.set("location",a.location),_.Ua(a.links)||(a.links=[]),this.set("links",a.links),z6(this))};_.m.imageDateControl_changed=function(){z6(this)};_.m.tileZoom_changed=function(){this.Ca()};
_.m.tiles_changed=function(){var a=this.get("tiles"),b,c=a&&(0,window.parseFloat)(a.centerHeading||a.originHeading);this.set("headingOffset",180-(c||0));if(a){if(_.C(c)){b=-(0,window.parseFloat)(a.originPitch||"0");var d=(0,window.parseFloat)(a.originPitchYaw);(0,window.isNaN)(d)||(b*=Math.cos(_.A(c-d)));b={heading:c,pitch:b}}this.P=c=a.tileSize;this.Xa=d=a.worldSize;this.Ka=c&&d&&Math.ceil(Math.max(_.fj(d.width/c.width),_.fj(d.height/c.height)));this.ta=a.getTileUrl;A6(this,!0);this.Ca()}this.set("photographerPov",
b)};_.m.inMotion_changed=function(){0==this.get("inMotion")&&this.Ca()};_.m.zoom_changed=function(){A6(this)};_.m.location_changed=function(){var a=this.getLocation();if(a){var b=a.pano,c=a.latLng,a=a.description;b!==this.getPano()&&this.set("pano",b);c!==this.getPosition()&&this.set("position",c);a!=this.get("description")&&this.set("description",a);this.Ca()}};_.m.pov_changed=function(){3!=_.W.type?this.Ca():this.U()};_.m.size_changed=function(){A6(this);this.Ca()};
_.m.visible_changed=function(){this.get("visible")||this.wg();this.Ca()};_.m.wg=_.la();_.m.getLocation=_.K("location");_.m.getPosition=_.K("position");_.m.getPano=_.K("pano");_.m.getPov=_.K("pov");_.m.vd=_.K("size");_.m.getTileUrl=function(a,b,c,d){return this.get("disabled")?_.kv:this.ta?this.ta(a,b,c,d):this.Jb.getTileUrl("tile",c,d,b)+"&panoid="+a+"&fover=2&onerr=3"};_.m.fe=_.K("tileZoom");_.m.Hd=_.K("worldSize");_.m.Kg=_.K("headingOffset");_.m.pi=_.K("projection");
_.m.xf=function(){return this.qa||this.get("inMotion")};_.m.disabled_changed=function(){this.S.style.backgroundColor=this.get("disabled")?"black":""};_.m=B6.prototype;_.m.Re=function(a,b,c,d){var e=_.A(c.pitch),f=_.A(c.heading);b=Math.cos(e);var e=Math.sin(e),g=Math.cos(f),h=Math.sin(f),k=a.width/2,f=k*Math.pow(2,c.zoom-1);a=a.height/2-d.y;var n=b*f-e*a,k=k-d.x;d=g*n+h*k;g=g*k-h*n;return new _.xc(_.Ka(Math.atan2(-g,d)),_.Ka(Math.atan2(e*f+b*a,Math.sqrt(d*d+g*g))),c.zoom)};
_.m.Qe=function(a,b,c,d){b=a.width/2;var e=b*Math.pow(2,c.zoom-1),f=a.height/2-d.y;d=b-d.x;a=-Math.tan(_.A(c.heading));var g=Math.tan(_.A(c.pitch))*Math.sqrt(1+Math.pow(a,2));b=Math.sqrt(Math.pow(e,2)+Math.pow(f,2)+Math.pow(d,2))/Math.sqrt(1+Math.pow(g,2)+Math.pow(a,2));var h,k;h=-g*b-f;k=2*e;f-=g*b;g=k*k-4*h*f;0>g&&(g=0);h=h?(-k+Math.sqrt(g))/(2*h):-f/k;e=_.Ka(2*Math.atan(h));h=-a*b-d;k=2*b;f=a*b-d;g=k*k-4*h*f;0>g&&(g=0);h=h?(-k+Math.sqrt(g))/(2*h):-f/k;d=_.Ka(2*Math.atan(h));a=(d-c.heading)%360;
90<a&&(d=(d-180)%360);-90>a&&(d=(d+180)%360);return new _.xc(d,e,c.zoom)};_.m.Lf=function(a,b,c,d,e){var f=_.A(d.heading+e);e=Math.cos(_.A(d.pitch));var g=Math.sin(_.A(d.pitch)),h=Math.cos(f),f=Math.sin(f),k=b.width/2;d=k*Math.pow(2,d.zoom-1);b=b.height/2-a.y;var k=k-a.x,n=e*d-g*b;a=h*n+f*k;f=h*k-f*n;h=Math.atan2(-f,a);0>h&&(h+=2*Math.PI);e=Math.atan2(g*d+e*b,Math.sqrt(a*a+f*f));this.O.x=h*c.width/(2*Math.PI);this.O.y=c.height*(.5-e/Math.PI);return this.O};
_.m.Lj=function(a,b,c,d,e){var f=new _.L(90-180*a.y/c.height,360*a.x/c.width),g=new _.L(d.pitch,d.heading);return _.qA(f,g)>=Math.PI/2?null:C6(this,a,b,c,d,e)};
_.m.Ei=function(a,b,c,d,e,f,g,h,k){var n=this.O;n.x=_.Ia(e,0,360)/360*h.width;n.y=.5*h.height;var p=C6(this,n,g,h,f,k),q=Math.sqrt(_.MC(p,a));e=p.x;p=p.y;(0,window.isFinite)(e)&&(0,window.isFinite)(p)||(e=q=window.Infinity,p=0);var q=Math.sin(Math.atan(q/c/4)),r;r=p==a.y&&e==a.x?0:Math.atan((p-a.y)/(e-a.x))+Math.atan(d/q);var v=Math.sqrt(d*d+1);this.j[0].x=a.x+Math.cos(r)*v*c*q;this.j[0].y=a.y+Math.sin(r)*v*c*q;n.x=_.Ia(b.x-k/360,0,1)*h.width;n.y=b.y-.05;f=C6(this,n,g,h,f,0);b=1.5*Math.PI;f.j(a)||
(b-=Math.atan((f.x-a.x)/(f.y-a.y)));this.j[1].x=this.j[0].x+Math.cos(b)*c*d*2;this.j[1].y=this.j[0].y+Math.sin(b)*c*d*2;a=this.j[1].y==p&&this.j[1].x==e?Math.PI:Math.PI+Math.atan((this.j[1].y-p)/(this.j[1].x-e));this.j[2].x=this.j[1].x+Math.cos(a)*c*q*2;this.j[2].y=this.j[1].y+Math.sin(a)*c*q*2;a=e==this.j[0].x&&p==this.j[0].y?0:Math.atan((p-this.j[0].y)/(e-this.j[0].x));c=(Math.cos(b)*(this.j[0].y-this.j[2].y)-Math.sin(b)*(this.j[0].x-this.j[2].x))/(Math.sin(b)*Math.cos(a)-Math.cos(b)*Math.sin(a));
this.j[3].x=this.j[0].x+c*Math.cos(a);this.j[3].y=this.j[0].y+c*Math.sin(a);for(c=0;4>c;c++)this.j[c].round();return this.j};_.y(D6,y6);D6.prototype.pano_changed=function(){this.j=!1;y6.prototype.pano_changed.call(this)};D6.prototype.tiles_changed=function(){this.j=!1;y6.prototype.tiles_changed.call(this)};
D6.prototype.Ia=function(){var a=this.vd(),b=a.height,c=a.width,d=this.V;if(0!=a.height&&0!=a.width)if(d.width!=c&&(d.width=c),d.height!=b&&(d.height=b),this.getPano()&&this.getPov()&&this.P&&_.C(this.fe())){_.mk(d);if(!this.T){this.T=!0;this.O=new t6;a=this.O;if(d.getContext)for(var b=null,c=["webgl","experimental-webgl","webkit-3d","moz-webgl"],e=0;e<c.length;++e){try{b=d.getContext(c[e])}catch(v){}if(b)break}else b=null;a.j=b;a.j?(a.j.clearColor(1,1,1,1),a.j.clearDepth(1E4),a.j.clear(a.j.COLOR_BUFFER_BIT|
a.j.DEPTH_BUFFER_BIT),a.j.disable(a.j.CULL_FACE),a.j.depthMask(!1),a.j.disable(a.j.DEPTH_TEST),a.j.enable(a.j.BLEND),a.j.blendFunc(a.j.SRC_ALPHA,a.j.ONE_MINUS_SRC_ALPHA),Tca(a)?(v6(a,d),a=!0):a=!1):a=!1;if(!a){this.O=null;return}}if(a=this.O){if(!this.j){this.j=!0;var f={},b=this.Xa,c=this.P;b&&c&&(f.P=b.width,f.O=b.height,f.Fh=c.width,f.Pf=c.height);f.j=this.Kg();f.id=this.getPano();f.getTileUrl=(0,_.t)(this.getTileUrl,this);a.j.flush();a.O&&a.O.clear();a.O=new n6;b=a.O;b.Aa=a.j;b.V=f;c=f.O/f.Pf;
e=f.P/f.Fh;b.U=Math.ceil(c);b.T=Math.ceil(e);b.j=Math.ceil(Math.log(e)/Math.log(2));b.ta=f.O/(f.Pf*b.U);b.oa=f.P/(f.Fh*b.T);b.O=Array(b.j+1);for(var f=1,g=(0,_.t)(b.Io,b),h=b.j;0<=h;--h){var k=new m6(b.j,g,h,Math.ceil(c*f),Math.ceil(e*f));b.O[h]=k;f*=.5}b.S=b.O[0].getTile(0,0);for(c=0;c<b.j;++c)for(e=b.O[c],f=b.O[c+1],g=e.P,h=e.j,k=0;k<g;++k)for(var n=0;n<h;++n)for(var p=e.getTile(k,n),q=0;1>=q;++q)for(var r=0;1>=r;++r)p.Of[2*q+r]=f.getTile(2*k+q,2*n+r);b.P=[];o6(b,b.S);b.Ea=window.setInterval((0,_.t)(b.xm,
b),100);a.O.na=(0,_.t)(t6.prototype.Zb,a);a.oa&&(b=a.oa,b.U&&(b.j.deleteBuffer(b.U),b.U=null),b.V&&(b.j.deleteBuffer(b.V),b.V=null),b.O&&(b.j.deleteBuffer(b.O),b.O=null));a.oa=new Rca(a.j,a.O)}b=this.getPov();v6(a,d);d=_.A(b.heading);a.ta=_.A(b.pitch);a.qa=d;d=b.zoom;d!=a.Ea&&(a.Ea=d,a.V=2*_.Ka(Math.atan(Math.tan(.25*Math.PI)/Math.pow(2,d-1))),w6(a));a.Zb()}}else _.AC(d)};_.m=E6.prototype;_.m.Re=function(a,b,c,d){var e=a.width/b.width*4*Math.pow(2,c.zoom-1);return new _.xc(c.heading+(d.x-a.width/2)/b.width*360/e,c.pitch-(d.y-a.height/2)/b.height*180/e,c.zoom)};_.m.Qe=function(a,b,c,d){var e=a.width/b.width*4*Math.pow(2,c.zoom-1);return new _.xc(c.heading-(d.x-a.width/2)/b.width*360/e,c.pitch+(d.y-a.height/2)/b.height*180/e,c.zoom)};
_.m.Lj=function(a,b,c,d,e){var f=this.O,g=Math.pow(2,d.zoom-1),h=180*a.y/c.height-90+d.pitch;f.x=b.width*(_.Ia(a.x/c.width*360-d.heading-e,-180,180)/90*g+.5);f.y=h/90*g*b.width+b.height/2;return f};_.m.Lf=function(a,b,c,d,e){var f=Math.pow(2,d.zoom-1),g=(-b.height/2+a.y)/b.width*90/f;this.O.x=_.Ia(90*(a.x/b.width-.5)/f+e+d.heading,0,360)/360*c.width;this.O.y=(g-d.pitch+90)/180*c.height;return this.O};
_.m.Ei=function(a,b,c,d,e){e=_.Ia(e-360*b.x,0,180);var f=Math.abs(e-90)/90,g=-2*(b.y-.5);b=1-f;90<e&&(b=-b);b*=c;e=c*d/2*(-2+f+f*g*10);f=c*d/2*(2-f+f*g*10);this.j[0].x=a.x-b;this.j[0].y=a.y-d*c;this.j[1].x=a.x-b;this.j[1].y=a.y+d*c;this.j[2].x=a.x+b;this.j[2].y=a.y+f;this.j[3].x=a.x+b;this.j[3].y=a.y+e;for(a=0;4>a;a++)this.j[a].round();return this.j};_.y(F6,y6);_.m=F6.prototype;_.m.Ki=function(a){a&&(window.clearTimeout(a.uk),a.release(),_.ji(this.O,a,1))};_.m.jn=function(){G6(this);this.T=window.setTimeout((0,_.t)(this.Li,this),500)};_.m.Li=function(){_.G(this.O,function(a){window.clearTimeout(a.uk);a.release()});this.O.length=0;G6(this);this.j&&this.j.set("tileFadeMode",1)};_.m.pov_changed=function(){var a=this.getPov();if(a&&_.C(a.pitch)){var b=_.Ha(a.pitch,-45,45);a.pitch!=b&&this.set("pov",new _.xc(a.heading,b,a.zoom))}y6.prototype.pov_changed.call(this)};
_.m.wg=function(){this.Ea=!0;this.Ca()};
_.m.Ia=function(){var a=this.getPov(),b=this.P,c=this.Hd(),d=this.fe(),e=this.vd();if(b&&e&&c&&_.C(d)&&a&&_.C(a.zoom)&&_.C(a.heading)&&_.C(a.pitch))if(d=e.width/c.width*4*Math.pow(2,a.zoom-1),this.Ea)this.Ea=!1,this.Li(),this.Ki(this.j),this.j=null;else{var f=this.get("pano"),g=this.j&&this.j.get("mapType"),h=this.get("zoom"),k=Math.ceil(b.width*d),b=Math.ceil(b.height*d);if(!g||g.tileSize.width!=k||g.tileSize.height!=b||f!=g.Nd||g.zoom!=h){if(g=this.j)_.I.removeListener(this.Oa),g.uk=window.setTimeout((0,_.t)(this.Ki,
this,g),5E3),this.O.push(g);g=this.j=new _.tv(this.S,this.kb);g.set("tileFadeMode",1!=_.W.type&&this.O.length?2:0);G6(this);this.Oa=_.I.addListenerOnce(g,"tilesloaded",(0,_.t)(this.jn,this));this.j.set("mapType",{Nd:f,zoom:h,tileSize:new _.O(k,b),getTile:(0,_.t)(this.Zn,this),maxZoom:5,Wd:!0});this.j.set("zoom",h);this.V=void 0}this.j&&(f=a.heading+this.Kg(),this.V&&(f=this.V+_.Ia(f-this.V,-180,180)),this.V=f%7200,h=d/360,d=f*c.width*h,a=2*(90-a.pitch)*c.height*h,c=new _.jf,c.ua=Math.round(d-e.width/
2),c.wa=Math.round(d+e.width/2),c.ra=Math.round(a-e.height/2),c.ya=Math.round(a+e.height/2),this.j.set("projectionBounds",c),this.j.set("offset",new _.O(c.ua,c.ra)),this.j.set("size",this.get("size")))}};
_.m.Zn=function(a,b,c){b=this.j.get("mapType");var d=c.createElement("div"),e=this.Hd(),f=this.P;if(e&&f){var g=a.x,h=e.width/f.width;if(0<h){for(;0>g;)g+=h;for(;g>=h;)g-=h}e=Math.ceil(e.height/f.height);if(0>a.y||a.y>=e)return d;var k,n=0,e=function(){++n==k&&(_.ok(d),_.I.trigger(d,"load"))},e={Bc:e,xe:e,size:b.tileSize},p=Math.floor(g);k=g==p?1:2;var f=this.getTileUrl(this.getPano(),this.fe(),p,a.y),q=new _.N((p-g)*b.tileSize.width,0);_.nk(d);H6(c,d,f,q,e);if(g!=p){for(p+=1;0<h&&p>=h;)p-=h;f=this.getTileUrl(this.getPano(),
this.fe(),Math.floor(p),a.y);q=new _.N((p-g)*b.tileSize.width,0);H6(c,d,f,q,e)}}return d};_.y(N6,y6);N6.prototype.tileZoom_changed=function(){y6.prototype.tileZoom_changed.call(this);O6(this)};N6.prototype.pano_changed=function(){y6.prototype.pano_changed.call(this);this.O&&_.G(this.O,function(a){a.tf=!1;a.Rf=null;a.Vg=!1;a.jb&&_.ZB(a.jb)});O6(this)};N6.prototype.wg=function(){this.T=!0;this.Ca()};
N6.prototype.Ia=function(){var a=this.vd(),b=a.height,a=a.width,c=_.sk.j,d=c&&this.xf()&&786432<b*a;d&&(a=Math.round(a/2),b=Math.round(b/2));if(this.j.width!=a||this.j.height!=b)d?(this.j.style[c]="scale(2)",_.hk(this.j,new _.N(a/2,b/2)),this.V=!0):this.V&&(this.j.style[c]="",_.hk(this.j,_.tg),this.V=!1),this.j.width=a,this.j.height=b;if(this.T)this.T=!1,this.Ea.clearRect(0,0,a,b);else{var c=a,d=b,e=c/2,f=d/2,g=Math.sqrt(e*e+f*f);_.G(this.O,function(a){a.Rf=[]});var h=new Vca;h.Ec=this.getPov();h.j=
this.Kg();h.width=a;h.height=b;h.tileSize=this.P;h.O=this.fe();h.worldSize=this.Hd();h.P=this.O;h.Nd=this.getPano();h.S=this.Ea;h.T=this.xf();h.Nd&&h.Ec&&h.tileSize&&_.C(h.O)&&!this.get("disabled")?(_.mk(this.j),P6(this,new I6(0,0,e,0,e,f,e,f,g),h),P6(this,new I6(e,0,c,0,e,f,e,g,f),h),P6(this,new I6(c,0,c,f,e,f,f,e,g),h),P6(this,new I6(c,f,c,d,e,f,f,g,e),h),P6(this,new I6(c,d,e,d,e,f,e,f,g),h),P6(this,new I6(e,d,0,d,e,f,e,g,f),h),P6(this,new I6(0,d,0,f,e,f,f,e,g),h),P6(this,new I6(0,f,0,0,e,f,f,g,
e),h)):_.AC(this.j)}};_.y(S6,y6);_.m=S6.prototype;_.m.jp=function(){this.O=!0;this.set("pov",this.j.getPov());this.O=!1};_.m.kp=function(){this.O=!0;this.set("pano",this.j.getPano());this.O=!1};_.m.clickToGo_changed=function(){if(!this.O&&this.j){var a=this.get("clickToGo");this.j.enableClickToGo(0!=a)}};_.m.scrollWheel_changed=function(){if(!this.O&&this.j){var a=this.get("scrollWheel");this.j.enableScrollToZoom(0!=a)}};_.m.panoProvider_changed=function(){if(!this.O&&this.j){var a=this.get("panoProvider");this.j.registerPanoProvider(a)}};
_.m.pov_changed=function(){if(!this.O&&this.j){var a=this.get("pov");this.j.setPov(a)}};_.m.pano_changed=function(){y6.prototype.pano_changed.call(this);if(!this.O&&this.j){var a=this.get("pano");this.j.setPano(a)}};_.m.Ia=_.la();_.y(T6,_.J);_.m=T6.prototype;_.m.zoom_changed=function(){var a=this.jg();if(_.C(a)&&!(0,window.isNaN)(a)){var b=_.Su(this.get("zoomRange"),a);a!=b?this.ri(b):(b=this.Yc())&&b.zoom==a||this.xd(new _.xc(b?b.heading:0,b?b.pitch:0,a))}};_.m.heading_changed=function(){var a=this.fj();if(_.C(a)&&!(0,window.isNaN)(a)){var b=this.Yc();b&&b.heading==a||this.xd(new _.xc(a,b?b.pitch:0,b?b.zoom:0))}};
_.m.pov_changed=function(){var a=this.Yc();if(a){var b=this.jg();a.zoom!=b&&this.ri(a.zoom);b=this.fj();a.heading!=b&&this.wq(a.heading)}};_.m.sm=function(a,b){var c=this.Yc();this.xd(new _.xc(120*a+c.heading,-40*b+c.pitch,c.zoom))};_.m.tm=function(a,b){var c=this.Yc();this.xd(new _.xc(5*a+c.heading,-5*b+c.pitch,c.zoom))};
_.m.um=function(a){var b=this.get("size"),c=this.get("layoutBounds")||_.kf(0,0,b.width,b.height),d=new _.N(0,0);a.ra<c.ra?d.y=c.ra-a.ra:a.ya>c.ya&&(d.y=c.ya-a.ya);a.ua<c.ua?d.x=c.ua-a.ua:a.wa>c.wa&&(d.x=c.wa-a.wa);a=this.get("worldSize");var c=this.get("projection"),e=this.Yc(),e=c.Re(b,a,e,_.tg),e=c.Qe(b,a,e,d);this.xd(e)};
_.m.vm=function(a){if(!_.ii(a)){if(this.Sf){this.Sf=!1;var b=_.gl(a,this.j);0==this.get("disableDoubleClickZoom")&&U6(this,-1,b);window.clearTimeout(this.O)}else this.Sf=!0,this.O=_.IA(this,function(){this.Sf=!1},250);_.Za(a)}};_.m.bp=function(a){_.ii(a)||0!=this.get("disableDoubleClickZoom")||(a=_.gl(a,this.j),U6(this,1,a))};_.m.rm=function(a,b){U6(this,.33*b,a)};_.m.ri=_.Gb("zoom");_.m.jg=_.K("zoom");_.m.wq=_.Gb("heading");_.m.fj=_.K("heading");_.m.xd=_.Gb("pov");_.m.Yc=_.K("pov");_.y(V6,_.S);V6.prototype.internalPov_changed=function(){if(!this.j&&!this.oa){var a=this.get("internalPov"),b=this.get("devZoom");this.j=!0;this.set("devPov",a);b!=a.zoom&&this.set("devZoom",a.zoom);this.j=!1}};V6.prototype.devPov_changed=function(){this.j||this.Ca()};V6.prototype.devZoom_changed=function(){if(!this.j){var a=this.get("devPov");a&&_.C(a.zoom)&&(a.zoom=this.get("devZoom"));this.Ca()}};
V6.prototype.Ia=function(){var a=this.get("devZoom"),b=this.get("devPov")||{heading:0,pitch:0};this.j=!0;_.C(b.zoom)&&!_.C(a)&&this.set("devZoom",b.zoom);_.C(b.zoom)||(a=_.C(a)?a:1,b.zoom=a);this.set("internalPov",b);this.j=!1};_.y(W6,_.J);W6.prototype.visible_changed=function(){var a=0!=this.get("visible");_.BC(this.O,a);_.I.trigger(this.O,"resize")};
W6.prototype.takeDownUrl_changed=W6.prototype.pov_changed=W6.prototype.pano_changed=function(){var a=this.get("pov"),b=this.get("pano"),c=this.get("takeDownUrl");a&&(c||b)&&(a="1,"+a.heading+",,"+Math.max(0,a.zoom-1||0)+","+-a.pitch,b=c?c+("&cbp="+a+"&hl="+_.He(_.Ke(_.R))):this.Jb.getUrl("report",["panoid="+b,"cbp="+a,"hl="+_.He(_.Ke(_.R))]),this.j.setAttribute("href",b),this.set("rmiLinkData",{label:"\u62a5\u544a\u95ee\u9898",tooltip:"\u5411 Google \u62a5\u544a\u8857\u666f\u56fe\u50cf\u95ee\u9898",
url:b}))};X6.prototype.W=_.l("N");_.Ba(Y6,_.PH);Y6.prototype.fill=function(a){_.MH(this,a&&a.W())};var Z6="t-bDow0pNywiw";_.Ej(e7,_.J);
e7.prototype.pano_changed=e7.prototype.pov_changed=e7.prototype.na=function(){var a=this.get("pov"),b=this.S,c=this.get("pano"),d=this.get("location");if(a&&d){var e=new _.zJ,f=_.GK(e);f.N[0]=1;var g=_.OK(f);g.N[0]=0;g.setHeading(a.heading);g.setTilt(90+a.pitch);_.MK(g,d.latLng.lat());_.LK(g,d.latLng.lng());g.N[6]=_.Ka(2*Math.atan(.75*Math.pow(2,1-a.zoom)));a=_.PK(f);c&&"F:"==c.substring(0,2)?(a.N[0]=c.substring(2),a.N[1]=4):c&&(a.N[0]=c,a.N[1]=0);cda(b,_.XL(e,this.O));_.gM(this.j,this.P,[b],_.la())}};
e7.prototype.location_changed=function(){var a=this.get("pov"),b=this.S,c=this.get("location");if(c){5 in b.N&&delete b.N[5];c&&c.profileUrl&&!this.V&&(b.N[5]=c.profileUrl);dda(b,this.O+"/@"+c.latLng.lat()+","+c.latLng.lng()+",13z"+this.U);var d,e;if(c.description){if(d=c.shortDescription,e=c.description,0==e.indexOf(d)){e=e.substr(d.length);var f=e.match(/^[,.!;\s]*/);e=e.substr(f[0].length)}}else d=ada(b)||"\u65e0\u5730\u5740",e=bda(b)||"\u65e0\u5730\u5740",f={latLng:new _.L(c.latLng.lat(),c.latLng.lng())},
this.T.geocode(f,(0,_.t)(function(f,h){if(this.get("location")==c){if(h==_.ga&&f[0]){var k=f[0];d=e="";for(var n=k.address_components.length-1;0<=n;n--){var p=k.address_components[n];if(0<=_.hc(p.types,"political"))if(e){d=p.long_name;break}else e=p.long_name}}else e=d="\u65e0\u5730\u5740";b.N[0]=d;b.N[1]=e;a&&c&&_.gM(this.j,this.P,[b],_.la())}},this));b.N[0]=d;b.N[1]=e;a&&this.na()}};f7.prototype.W=_.l("N");_.Ba(g7,_.PH);g7.prototype.fill=function(a){_.MH(this,a&&a.W())};var h7="t-_EPk2VOG1I0";_.Ej(i7,_.J);i7.prototype.enableCloseButton_changed=function(){var a=!!this.get("enableCloseButton");_.BC(this.j,a);_.I.trigger(this.j,"resize")};j7.prototype.U=function(){this.O?(window.document.exitFullscreen||window.document.webkitExitFullscreen||window.document.mozCancelFullScreen||window.document.msExitFullscreen).call(window.document):(this.j.requestFullscreen||this.j.webkitRequestFullscreen||this.j.mozRequestFullScreen||this.j.msRequestFullscreen).call(this.j)};j7.prototype.S=function(){_.I.trigger(this.T,"resize");this.O=!this.O;this.P&&(this.P.style.left=_.V(this.O?-26:0))};var jda=function(){var a;return _.Gg?(a=/Windows NT ([0-9.]+)/,(a=a.exec(_.gc))?a[1]:"0"):_.Fg?(a=/10[_.][0-9_.]+/,(a=a.exec(_.gc))?a[0].replace(/_/g,"."):"10"):_.Ig?(a=/Android\s+([^\);]+)(\)|;)/,(a=a.exec(_.gc))?a[1]:""):_.Jg||_.Kg?(a=/(?:iPhone|CPU)\s+OS\s+(\S+)/,(a=a.exec(_.gc))?a[1].replace(/_/g,"."):""):""}();var m7=_.Nc("Firefox"),Gda=_.Qc()||_.Nc("iPod"),Hda=_.Nc("iPad"),Ida=_.Nc("Android")&&!(K4()||_.Nc("Firefox")||_.Oc()||_.Nc("Silk")),n7=K4(),Jda=_.Nc("Safari")&&!(K4()||_.Nc("Coast")||_.Oc()||_.Nc("Edge")||_.Nc("Silk")||_.Nc("Android"))&&!(_.Qc()||_.Nc("iPad")||_.Nc("iPod"));(function(){if(m7)return k7(/Firefox\/([0-9.]+)/);if(_.Uc||_.Tc||_.Eg)return _.Lg;if(n7)return k7(/Chrome\/([0-9.]+)/);if(Jda&&!(_.Qc()||_.Nc("iPad")||_.Nc("iPod")))return k7(/Version\/([0-9.]+)/);if(Gda||Hda){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(_.gc))return a[1]+"."+a[2]}else if(Ida)return(a=k7(/Android\s+([0-9.]+)/))?a:k7(/Version\/([0-9.]+)/);return""})();var r7=new _.BF(window.document);_.y(s7,_.J);var t7=[new _.N(126,67),new _.N(4,67),new _.N(63,9),new _.N(63,127)],z7=[new _.N(166,103),new _.N(-18,103),new _.N(70,-15),new _.N(70,215)];s7.prototype.Aa=function(){var a=this.get("mode");_.B(a)&&_.hM(a)&&(_.AC(this.oa),_.tk(this.j,1),this.na=!0,_.mk(this.S),_.CC(this.U,this.get("description")||""))};s7.prototype.mode_changed=function(){var a=this.get("mode");_.hM(a)||_.AC(this.S)};
s7.prototype.pixelPosition_changed=function(){var a=this.get("pixelPosition"),b=this.get("pixelBounds");if(a&&b){var c=3,d=a.x,a=a.y,e=z7[3].x,f=z7[3].y;d<b.ua+e+30?c=1:d>b.wa+e-this.V.Ma.width-30?c=0:a<b.ra+f-this.O.Ma.height&&a<b.ya-z7[2].y-t7[3].y-this.O.Ma.height&&(c=2);c!=this.P&&(this.P=c,b=this.O,e=b.items[0].lb,_.$B(this.qa,b.Ma,new _.N(e.x+b.mb.x*c,e.y+b.mb.y*c),b.Ya.size),_.hk(this.qa,t7[c]));c=z7[c];this.T.x=d-c.x;this.T.y=a-c.y;_.hk(this.S,this.T)}this.na&&(_.CC(this.U,"\u6b63\u5728\u52a0\u8f7d..."),
_.tk(this.j,.25),this.na=!1)};s7.prototype.thumbnailPanoId_changed=function(){var a=this.get("thumbnailPanoId");if(a){var a="F:"==a.substring(0,2)?_.Q(x3(this.Cd).N,10)[0]+"/"+a.substring(2)+"/w94-h75-n-k-no/":this.ta("thumbnail",["w=94","h=75","thumbfov=90","thumb=2","it=all","panoid="+a]),b=this.j;_.uB(b,a,b.O)}else _.mk(this.oa),_.CC(this.U,"\u65e0\u53ef\u7528\u6570\u636e\u3002")};var zda={"default":"all",outdoor:"1"},v7=function(a,b,c,d){if(a.pano)a=Kda(a),_.uJ()?Cda(a.pano,b,d):w7("panoid",a.pano,null,b,c);else if(a=Lda(a),_.uJ())Eda(a,b,d);else{d=Math.floor(a.radius)||50;var e="best"==a.preference?"best":"closest",f=a.source||"default";w7("ll",a.location.toUrlValue(),d,b,c,f,e)}},Kda=_.wb({pano:_.ng},!1),Lda=_.wb({location:_.Tb,radius:_.og,preference:_.Eb(_.zb(_.lh)),source:_.Eb(_.zb(_.mh))},!1);_.m=y7.prototype;
_.m.Mp=function(a){var b=a.O=a.O||{};b.j||(b.j=new _.J);var c=new _.oI(_.yA(),a.get("client"));kda(b,a);b.j.set("zoomRange",new _.Ru(0,5));lda(b,a);ida(b,a,c);var d=b.O;_.B(a.__gm.get("fontLoaded"))||a.__gm.bindTo("fontLoaded",new _.Ix(_.gk(d)));_.M("controls",function(e){var f=new e.ei(d),g=new e.Lk(f,d,null,a.controls,null,null,a,!1,null,null);g.set("streetViewControl",!1);var h=b.j;g.bindTo("attributionText",h,"copyright");g.set("mapTypeId","streetview");g.set("tilt",!0);g.bindTo("heading",h);
g.bindTo("zoom",h,"zoomFinal");g.bindTo("zoomRange",h);g.bindTo("pov",h,"povFinal");g.bindTo("position",a);g.bindTo("pano",a);g.bindTo("passiveLogo",a);g.bindTo("floors",h);g.bindTo("floorId",h);g.bindTo("rmiWidth",a);g.bindTo("panControlOptions",a,null,!0);g.bindTo("zoomControlOptions",a,null,!0);g.bindTo("panControl",a);g.bindTo("zoomControl",a);g.bindTo("disableDefaultUI",a);g.bindTo("fontLoaded",a.__gm);g.bindTo("size",h);_.I.addListener(h,"copyright_changed",function(){a.set("streetViewDataProviders",
h.get("copyright"))});g.U();_.I.forward(g,"panbyfraction",b);mda(b,a,e);_.sj()||_.FC()?(qda(b,a,f),oda(b,a,f),pda(b.O,f)):(rda(b,a,f),sda(b,a,f));tda(b,f);uda(b,a,f,c);vda(a);h.bindTo("layoutBounds",f,"bounds");e.lk(a.getContainer())});_.I.addListener(a,"closeclick",function(){a.set("visible",!1)});a.j&&wda();Oca(a);a.get("panoProvider")?_.Y(a,"Sc"):_.I.addListener(a,"panoprovider_changed",function(){a.get("panoProvider")&&_.Y(a,"Sc")});_.Y(a,"Sp");_.I.addDomListenerOnce(d,"mousedown",function(){_.Y(a,
"Sia")},!0);_.il("Sp","-p",a,!1);_.ll(a,"Sp");_.Ak(function(){_.ll(a,"Sp")})};_.m.ij=v7;_.m.im=x6;_.m.pm=s7;_.m.Hm=function(a){if(!a.j){var b=new _.vJ;a.j=new c6(b);a.j.bindTo("map",a)}(b=a.get("map"))?(_.Y(b,"Ls"),_.il("Ls","-p",a,!!b.Ga),_.il("Ls","-h",a,!!b.Ga)):_.jl("Ls","-p",a)};_.oc("streetview",new y7);});
